import {PET_CAPACITY,PET_TRAITS,PET_NEEDS,PET_ACTIONS} from './petState.js';
import {paintPanel} from './paintPanel.js';
export const escapePetText=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const esc=escapePetText;
const paths={paw:'M8 13c-2 0-5 3-5 5s3 3 5 2c2-1 2-1 4 0s5 0 5-2-3-5-5-5Z M5 7a2 3 0 1 0 .1 0 M10 4a2 3 0 1 0 .1 0 M15 7a2 3 0 1 0 .1 0',heart:'M12 20S3 14 3 8a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 6-9 12-9 12Z',food:'M3 11h18c0 7-3 9-9 9s-9-2-9-9Z M8 7V3 M12 7V2 M16 7V3',energy:'M14 2 5 14h7l-2 8 9-12h-7Z',fun:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z M6 6l12 12 M18 6 6 18 M3 12h18',moon:'M20 15A9 9 0 0 1 9 3a9 9 0 1 0 11 12Z',call:'M4 10v5h4l7 5V4l-7 6Z M19 8q4 4 0 8',book:'M3 4q5-2 9 1 4-3 9-1v15q-5-2-9 1-4-3-9-1Z M12 5v15',paint:'m4 15 11-11q3-2 5 1l-11 12Z M4 15q-3 2-2 6 5 0 7-4',plus:'M12 4v16 M4 12h16',back:'m14 5-7 7 7 7',close:'m6 6 12 12 M18 6 6 18',check:'m4 12 5 5L20 6'};
export const petIcon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.paw}"/></svg>`;
export const PET_CARE=[['pet','摸摸','亲近','heart'],['feed','喂零食','饱食','food'],['play','一起玩','趣味','fun'],['approach','叫过来','到你身边','call'],['rest','休息吧','精力','moon'],['carry','抱起来','抱着走','paw']];
const needIcon={food:'food',energy:'energy',social:'heart',fun:'fun'};
export function petMood(p){const low=Object.entries(p.needs).sort((a,b)=>a[1]-b[1])[0];return low[1]<35?{food:'肚子饿了',energy:'有点困了',social:'想被陪伴',fun:'想玩一会儿'}[low[0]]:'自在又开心';}
export const bondLabel=value=>value>=80?'形影不离':value>=40?'亲密伙伴':value>=10?'渐渐熟悉':'初识的小伙伴';
export function petPanelMarkup({life,home,catalog,selected,sourceId,tab,detailTab,error,portrait,context,removeConfirm=null}){
 const p=life.data.pets.find(p=>p.id===selected),a=p&&catalog.find(a=>a.id===p.assetId),source=home.rooms.flatMap(r=>r.items).find(i=>i.id===sourceId),room=id=>home.rooms.find(r=>r.id===id),paused=context.edit||context.overview||context.paused;
 const image=p=>`<img src="${portrait(p)}" alt="${esc(p.name)}" draggable="false">`;
 const journal=(id)=>{const entries=life.data.events.filter(e=>!id||e.petId===id).slice(-20).reverse();return `<div class="pet-journal"><h3>一起生活的小事</h3>${entries.map(e=>`<article>${petIcon('paw')}<div><strong>${esc(e.petName)}</strong><p>${esc(e.text)}</p></div></article>`).join('')||'<p class="pet-empty">第一次摸摸、第一次一起玩，都会留在这里。</p>'}</div>`;};
 const adoption=`<details class="pet-adoption" ${source||!life.data.pets.length?'open':''}><summary>${petIcon('plus')}${source?'让这个摆件成为宠物':'认识新伙伴'}<span>${life.data.pets.length} / ${PET_CAPACITY}</span></summary><form data-pet-adopt><label>选择宠物<select name="asset">${catalog.filter(a=>a.petSpecies&&(!source||a.id===source.assetId)).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></label><label>给它起个名字<input name="name" maxlength="24" placeholder="也可以先用默认名字"></label><fieldset><legend>它的性格 · 最多两种</legend>${Object.entries(PET_TRAITS).map(([id,label])=>`<label><input type="checkbox" name="trait" value="${id}"><span>${label}</span></label>`).join('')}</fieldset><button class="pet-primary" type="submit">${petIcon('paw')}${source?'成为家园宠物':'接它回家'}</button></form></details>`;
 const undo=life.lastRemoved&&!removeConfirm?`<div class="pet-remove-undo" role="status"><span>${esc(life.lastRemoved.name)}已移出家园<small>离开家园前可撤回</small></span><button data-pet-action="undo-remove">撤回移出</button></div>`:'';
 let content;
 if(p){
  const r=life.runtime.get(p.id),bond=Math.round(p.relations.user||0),here=p.roomId===home.activeRoomId;
  const tabs=`<nav class="pet-tabs" aria-label="宠物详情">${[['care','照顾'],['look','装扮'],['journal','小记']].map(([id,label])=>`<button data-pet-action="detail-tab" data-tab="${id}" aria-pressed="${detailTab===id}">${label}</button>`).join('')}</nav>`;
  content=`<div class="pet-profile"><div class="pet-profile-heading"><div><small>${esc(a.name)} · ${esc(room(p.roomId)?.name)}</small><h2>${esc(p.name)}</h2></div><span class="pet-mood" data-pet-mood>${petMood(p)}</span></div><div class="pet-stage" data-pet-motion="${paused?'idle':r?.kind||'idle'}"><span class="pet-stage-orbit"></span>${image(p)}<span class="pet-emote" aria-hidden="true"></span><span class="pet-stage-status" data-pet-status>${paused?'安心等你回来':PET_ACTIONS[r?.kind]||'发呆'}</span></div><div class="pet-traits">${p.traits.map(t=>`<span>${PET_TRAITS[t]}</span>`).join('')||'<span>随性</span>'}</div><div class="pet-bond">${petIcon('heart')}<span data-bond-label>${bondLabel(bond)}</span><progress data-pet-bond max="100" value="${bond}" aria-label="和你的亲密度"></progress><small data-bond-value>${bond} / 100</small></div></div>${tabs}`;
  if(detailTab==='care')content+=`<div class="h3-pets-needs">${Object.entries(PET_NEEDS).map(([key,label])=>`<div class="pet-need" data-low="${p.needs[key]<35}" data-need-row="${key}"><label>${petIcon(needIcon[key])}${label}<span data-need-text="${key}">${Math.round(p.needs[key])}</span></label><meter data-need="${key}" aria-label="${label}" min="0" max="100" value="${p.needs[key]}"></meter></div>`).join('')}</div><div class="pet-care-heading"><h3>陪它一会儿</h3><small>${here?'小小的照顾，慢慢变亲近':`它在${esc(room(p.roomId)?.name)}`}</small></div><div class="h3-pets-actions">${PET_CARE.map(([id,label,note,icon])=>`<button data-pet-action="interact" data-kind="${id}" ${(!here&&id!=='approach')||paused||r?.manual?'disabled':''}><span>${petIcon(icon)}</span><strong>${label}</strong><small>${note}</small></button>`).join('')}</div><div class="pet-action-feedback" role="status" aria-live="polite"><span data-pet-feedback>${paused?'布置结束后，再陪它玩吧。':here?'选一个动作，看看它的反应。':'点叫过来，让它来这个房间陪你。'}</span><progress data-action-progress max="1" value="0" hidden aria-label="互动进度"></progress></div>`;
  if(detailTab==='look')content+=`<div class="pet-dressing"><label>小伙伴的名字<input data-pet-name maxlength="24" value="${esc(p.name)}"></label><h3>给它换个配色</h3>${paintPanel(p,a,a.colorParts?.[0]?.color||'#b2a2cd',true)}</div>`;
  if(detailTab==='journal')content+=journal(p.id);
  content+=`<div class="pet-remove-entry"><button data-pet-action="remove">移出家园</button></div>`;
  if(removeConfirm===p.id)content=`<div class="pet-remove-confirm" role="alertdialog" aria-labelledby="pet-remove-title" aria-describedby="pet-remove-description"><h2 id="pet-remove-title">让${esc(p.name)}离开家园？</h2>${image(p)}<p id="pet-remove-description">它将从家园移出，空出一个宠物名额。已有小记会保留；本次离开家园前可以撤回，恢复名字、配色和亲密度。</p><div><button data-pet-action="cancel-remove">再陪陪它</button><button class="pet-remove-accept" data-pet-action="confirm-remove">确认移出</button></div></div>`;
 }else{
  content=`<div class="pet-roster-heading"><h2>家里的小伙伴</h2><p>${life.data.pets.length?`${life.data.pets.length} 位伙伴，各有自己的小脾气。`:'接一位小伙伴回家，一起慢慢熟悉。'}</p></div><nav class="pet-tabs" aria-label="宠物面板">${[['pets','伙伴'],['supplies','用品'],['journal','小记']].map(([id,label])=>`<button data-pet-action="tab" data-tab="${id}" aria-pressed="${tab===id}">${label}</button>`).join('')}</nav>`;
  if(tab==='pets')content+=`<div class="h3-pets-list">${life.data.pets.map(p=>`<button class="pet-card" data-pet-action="select" data-id="${esc(p.id)}">${image(p)}<strong>${esc(p.name)}</strong><small>${esc(room(p.roomId)?.name)}</small><span data-roster-status="${esc(p.id)}">${petMood(p)}</span></button>`).join('')}</div>${adoption}<label class="h3-pets-auto"><span>${petIcon('paw')}自由活动<small>让它们自己找点乐子</small></span><input type="checkbox" role="switch" data-pet-autonomy ${life.data.autonomy?'checked':''}></label>`;
  if(tab==='supplies')content+=`<div class="pet-supplies"><h3>备好它们的小日常</h3><p class="pet-note">食盆管饱，小球解闷，休息垫留给小懒虫。</p>${home.rooms.flatMap(r=>r.items.filter(i=>!i.stored&&i.assetId==='pet_bowls').map(i=>`<article>${petIcon('food')}<div><strong>${esc(r.name)}的食盆</strong><p class="pet-food-dots" aria-label="剩余 ${life.data.supplies[i.id]||0} 餐">${Array.from({length:5},(_,n)=>`<i data-filled="${n<(life.data.supplies[i.id]||0)}"></i>`).join('')}</p></div><button data-pet-action="refill" data-id="${esc(i.id)}">添粮</button></article>`)).join('')||'<p class="pet-empty">去家具里的「宠物用品」摆一个食盆吧，也可以先给小伙伴喂零食。</p>'}<p class="pet-note">离开家园时，它们会安心休息。</p></div>`;
  if(tab==='journal')content+=journal();
 }
 return `<section class="h3-pets-sheet" role="dialog" aria-modal="true" aria-label="家园宠物"><header><button class="pet-icon-button" data-pet-action="${p?'back':'close'}" aria-label="${p?'全部宠物':'关闭宠物面板'}">${petIcon(p?'back':'paw')}</button><strong>宠物小屋</strong><button class="pet-icon-button" data-pet-action="close" aria-label="关闭宠物面板">${petIcon('close')}</button></header><div class="h3-pets-body">${error?`<p class="pet-error" role="alert">${esc(error)}</p>`:''}${undo}${content}</div></section>`;
}
