export interface Home3DItem {id:string;assetId:string;x:number;y:number;z:number;rotation:number;color:string|null;stored:boolean;materialColors?:Record<string,string>;supportId?:string|null;dockId?:string|null;dockSlot?:string|null;dockDisabled?:boolean;length?:number}
export interface Home3DBoundary {kind:'wall_high'|'wall_low'|'wall_fence'|'open';door?:{kind:'door'|'arch'|'sliding'|'ribbon'|'oak'|'walnut'|'lattice';at:number;width:number}}
export interface Home3DRoom {id:string;name:string;x:number;z:number;level:number;wall:string;trim?:string;floor?:string;floorStyle?:'original'|'wood'|'tile'|'checker'|'stone'|'parquet'|'solid';wallStyle?:'solid'|'stripe'|'dot'|'panel'|'tile'|'timber'|'spa'|'framed';boundaries?:Partial<Record<'front'|'back'|'left'|'right',Home3DBoundary>>;items:Home3DItem[]}
export interface Home3DActivity {at:number;roomId:string;roomName:string;label:string;kind:'activity-start'}
export type HomeRecordSource='user'|'local'|'model';
export interface HomeRecord {id:string;at:number;kind:'message'|'action'|'presence';source:HomeRecordSource;actor:'user'|'character';text:string;roomId:string;roomName:string;initiative?:boolean;automatic?:boolean;replyTo?:string;turnId?:string;contextSegmentId?:string;editedAt?:number}
export interface HomeAction {id:string;kind:string;label:string;roomId:string;actor?:'character';target?:string;prerequisite?:string}
export interface HomeScene { perspective?:'first-person';manualRevision?:number;roomId:string;roomName:string;present:boolean;busy:boolean;activity:string;actions:HomeAction[];furniture?:Array<{id:string;name:string}>}
export interface HomePet {id:string;name:string;assetId:string;roomId:string;x:number;z:number;rotation:number;color:string|null;materialColors?:Record<string,string>;traits:string[];needs:{food:number;energy:number;social:number;fun:number};relations:Record<string,number>;memory:{lastFedBy?:string|null;lastPlayedBy?:string|null;favoriteSpot?:string|null;recentAction?:string|null};bondCooldown:number;sourceFurnitureId?:string|null}
export interface HomePetLife {version:1;autonomy:boolean;pets:HomePet[];supplies:Record<string,number>;events:Array<{petId:string;petName:string;at:number;text:string}>}
export interface Home3DState {version:1;assetVersion?:number;roomSizeVersion?:number;homePalette?:string;activityLog?:Home3DActivity[];records?:HomeRecord[];autonomy?:boolean;directSpeech?:boolean;speechFrequency?:'often'|'normal'|'quiet';activityFrequency?:'quiet'|'normal'|'lively';residentRoomId?:string|null;activeRoomId:string;rooms:Home3DRoom[];petLife?:HomePetLife}
