import React,{useMemo,useRef,useState} from 'react';
import {DECORATION_WORKSHOPS,type DecorationWorkshop} from '../../utils/decorationWorkshop';
import {cssImportPreset,readLegacyWhiteboxShare} from '../../utils/beautyCssAttribution';
import type {DecorationPreset} from '../../utils/chatDecoration';
import type {DecorationOrigin} from '../../utils/decorationLibrary';
import BeautyPresetPreview from './BeautyPresetPreview';
import './BeautyImportHub.css';
export default function BeautyImportHub({codePanel,busy,onFile,onCss,onCssBatch,initialCss}:{codePanel:React.ReactNode;busy:boolean;onFile:(file:File)=>void;onCss:(preset:DecorationPreset,origin:DecorationOrigin)=>Promise<void>;onCssBatch?:(items:{preset:DecorationPreset;origin:DecorationOrigin}[])=>Promise<void>;initialCss?:{text:string;name:string}}){
 const [tab,setTab]=useState<'code'|'css'|'file'>(initialCss?'css':'code');const files=useRef<HTMLInputElement>(null),photos=useRef<HTMLInputElement>(null);
 const [category,setCategory]=useState<DecorationWorkshop>('whitebox');
 const [text,setText]=useState(initialCss?.text||'');const [name,setName]=useState(initialCss?.name||'导入的白框');const [source,setSource]=useState<'self'|'imported'|''>('');const [credit,setCredit]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [preview,setPreview]=useState<DecorationPreset|null>(null);
 const legacy=useMemo(()=>{try{return readLegacyWhiteboxShare(text);}catch{return null;}},[text]);
 const parsed=useMemo(()=>{if(!text.trim())return null;try{return cssImportPreset(text,name,category);}catch{return null;}},[text,name,category]);
 const validate=()=>{const result=cssImportPreset(legacy?.[0]?.code||text,legacy?.[0]?.name||name.trim()||'导入的装扮',category);if(!result.origin&&!source)throw Error('请选择这份 CSS 是自制还是外部导入');return {...result,origin:result.origin||{kind:source as 'self'|'imported',credit:credit.trim()||undefined}};};
 const fileChange=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(file)onFile(file);};
 return <section className="beauty-import-hub"><nav aria-label="导入方式">{([['code','用码领取'],['css','直接 CSS'],['file','文件 / 图片']] as const).map(([id,label])=><button disabled={busy||saving} key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='code'&&codePanel}
 {tab==='file'&&<div className="beauty-import-files"><h3>把装扮带进来</h3><p>选择预设原文件，或带有装扮信息的分享原图。普通图片会作为聊天背景导入。</p><input hidden ref={files} type="file" accept="*/*" aria-label="装扮文件" onChange={fileChange}/><input hidden ref={photos} type="file" accept="image/*" aria-label="装扮相册图片" onChange={fileChange}/><button disabled={busy} onClick={()=>files.current?.click()}>从文件选择 <span>JSON / ZIP / CSS / TXT</span></button><button disabled={busy} onClick={()=>photos.current?.click()}>从相册选择 <span>分享原图 / 聊天背景</span></button></div>}
 {tab==='css'&&<div className="beauty-import-css">{legacy&&<p role="status">识别到旧版白框合集，共 {legacy.length} 份。确认来源后一起导入，预览展示第一份。</p>}{!legacy&&<label>装扮名称<input value={name} maxLength={60} onChange={e=>{setName(e.target.value);setPreview(null);}}/></label>}<label>粘贴 CSS / 旧版白框码<textarea aria-label="待导入 CSS" spellCheck={false} value={text} onChange={e=>{setText(e.target.value);setSource('');setPreview(null);setError('');}} placeholder="粘贴作者分享的完整 CSS，保留开头署名"/></label>
 {parsed?.origin?<div className="beauty-import-credit">署名：{parsed.origin.credit}<p>{parsed.origin.allowRemix===false?'禁止二改':parsed.origin.allowRemix===true?'允许二改':'未注明二改规则'} · {parsed.origin.allowRedistribute===false?'禁止二次传播':parsed.origin.allowRedistribute===true?'允许二次传播':'未注明传播规则'}</p></div>:<fieldset><legend>未识别到作者署名，请确认来源</legend>{!legacy&&<label>CSS 类型<select aria-label="CSS 类型" value={category} onChange={e=>{setCategory(e.target.value as DecorationWorkshop);setPreview(null);}}>{DECORATION_WORKSHOPS.filter(([id])=>id!=='sound').map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}<label><input type="radio" name="css-origin" checked={source==='self'} onChange={()=>setSource('self')}/>这是我自制的</label><label><input type="radio" name="css-origin" checked={source==='imported'} onChange={()=>setSource('imported')}/>外部导入</label><label>作者署名（选填）<input value={credit} maxLength={60} onChange={e=>setCredit(e.target.value)}/></label></fieldset>}
 {error&&<p role="alert">{error}</p>}<div className="beauty-import-actions"><button disabled={busy||saving||!text.trim()} onClick={()=>{try{setPreview(validate().preset);setError('');}catch(e){setError((e as Error).message);}}}>查看预览</button><button disabled={busy||saving||!text.trim()} onClick={async()=>{if(saving)return;setSaving(true);setError('');try{if(legacy){if(!onCssBatch)throw Error('请从统一导入入口导入合集');const items=legacy.map(item=>{const result=cssImportPreset(item.code,item.name);if(!result.origin&&!source)throw Error('请选择这份 CSS 是自制还是外部导入');return {preset:result.preset,origin:result.origin||{kind:source as 'self'|'imported',credit:credit.trim()||undefined}};});await onCssBatch(items);}else{const result=validate();await onCss(result.preset,result.origin);}setText('');setPreview(null);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>{saving?'导入中…':'保存到装扮库'}</button></div>{preview&&<BeautyPresetPreview data={preview}/>}</div>}
 </section>;
}
