import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=await import('file:///C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const c=JSON.parse(await fs.readFile('public/room3d/catalog.json','utf8')),bath=c.filter(a=>a.collection==='bathroom');let bytes=0,triangles=0;
for(const a of bath){const b=await fs.readFile('public/room3d/'+a.url),j=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));assert.ok(!j.images?.length&&!j.textures?.length);assert.ok(b.length<200000,a.id);let t=0;for(const m of j.meshes)for(const p of m.primitives){assert.ok(!p.attributes.TEXCOORD_0&&!p.attributes.COLOR_0);t+=j.accessors[p.indices].count/3;}assert.ok(t<6000,a.id);bytes+=b.length;triangles+=t;}
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader']});const errors=[];await fs.mkdir('output/bathroom',{recursive:true});
try{
 const p=await browser.newPage({viewport:{width:1100,height:850}});p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await p.goto('http://127.0.0.1:5174/test/fixtures/room3d-bathroom.html');await p.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});
 const state=()=>p.evaluate(()=>window.__homeEditor.inspect()),click=async(a,q='')=>{if(a==='panel'&&(await state()).panel===q.match(/data-panel="([^"]+)/)?.[1])return;await p.locator('[data-action="'+a+'"]'+q).first().click();};
 const limbs=()=>p.evaluate(()=>{const out=[];window.__visitor.root.traverse(o=>{if(o.name.startsWith('chibi-action-'))out.push({name:o.name,visible:o.visible,scale:o.scale.toArray()});});return out;});
 assert.equal((await state()).rooms[0].items.filter(i=>!i.stored).length,15);
 for(const motion of ['wave-cute','wave-calm','angry','dance']){await click('panel','[data-panel="chibi"]');await click('chibi-motion','[data-value="'+motion+'"]');await p.evaluate(()=>window.advanceTime(600));const l=await limbs();assert.equal(l.filter(o=>o.name.includes('hand')&&o.visible).length,2);assert.equal(l.filter(o=>o.name.includes('foot')&&o.visible).length,0);}
 await click('chibi-sit');await p.evaluate(()=>window.advanceTime(400));assert.equal((await limbs()).filter(o=>o.visible).length,4);await click('panel','[data-panel="chibi"]');await click('chibi-motion','[data-value="wave-cute"]');await p.evaluate(()=>window.advanceTime(700));assert.equal((await limbs()).filter(o=>o.visible).length,4);await click('chibi-view');await p.screenshot({path:'output/bathroom/stool-wave.png'});
 await click('panel','[data-panel="chibi"]');await click('chibi-stand');await click('chibi-motion','[data-value="wave-calm"]');await p.evaluate(()=>window.advanceTime(600));assert.equal((await limbs()).filter(o=>o.name.includes('foot')&&o.visible).length,0);await click('close');await p.screenshot({path:'output/bathroom/standing-hands-only.png'});
 await click('panel','[data-panel="chibi"]');await click('room-view');await p.evaluate(()=>window.__homeEditor.select('bath_tub'));await click('rotate');await click('place-rotation');let s=await state();assert.equal(s.rooms[0].items.find(i=>i.id==='bath_tray').rotation,90);assert.equal(s.rooms[0].items.find(i=>i.id==='bath_soap').rotation,90);await click('undo');await p.evaluate(()=>window.__homeEditor.select('bath_tub'));await click('store');s=await state();assert.ok(s.rooms[0].items.filter(i=>['bath_tub','bath_tray','bath_soap'].includes(i.id)).every(i=>i.stored));await click('undo');
 await click('panel','[data-panel="furniture"]');await click('category','[data-value="bathroom"]');assert.equal(await p.locator('.h3-asset').count(),15);await click('close');await p.screenshot({path:'output/bathroom/room.png'});await p.close();
 // Test every actual furniture through the same UI path, one displayed object at
 // a time. Stored instances remain below the 100-item limit; the gaming desk holds props.
 const page=await browser.newPage({viewport:{width:1100,height:850}});page.on('pageerror',e=>errors.push(String(e)));await page.goto('http://127.0.0.1:5174/test/fixtures/room3d-bathroom.html?empty');await page.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});
 const inspect=()=>page.evaluate(()=>window.__homeEditor.inspect()),act=(a,q='')=>page.locator('[data-action="'+a+'"]'+q).first().dispatchEvent('click');
 const meshColors=()=>page.evaluate(()=>{const s=window.__homeEditor.inspect(),scene=window.__visitor.root.parent.parent,out=[];scene.traverse(root=>{if(root.userData.itemId===s.selected&&root.userData.assetId){root.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])if(m.color)out.push({name:m.name,color:m.color.getHexString()});});}});return out;});
 const tested=[];for(const a of [c.find(a=>a.id==='gaming_desk'),...c.filter(a=>!['shell','gaming_desk'].includes(a.id))]){
  await act('panel','[data-panel="furniture"]');await act('category','[data-value="all"]');await act('add-item','[data-id="'+a.id+'"]');const before=await inspect();assert.equal(before.rooms[0].items.find(i=>i.id===before.selected)?.assetId,a.id,'add '+a.id+' '+before.message);const original=await meshColors();assert.ok(original.length,a.id);await act('palette');await page.locator('[data-furniture-color]').evaluate(el=>{el.value='#87a9ce';el.dispatchEvent(new Event('change',{bubbles:true}));});await page.evaluate(()=>window.advanceTime(0));const changed=await meshColors();assert.equal(changed.length,original.length);let count=0;for(let i=0;i<original.length;i++){if(a.paintMaterials.includes(original[i].name)){assert.equal(changed[i].color,'87a9ce',a.id+'/'+original[i].name);count++;}else assert.equal(changed[i].color,original[i].color,a.id+' secondary '+original[i].name);}assert.ok(count,a.id);tested.push(a.id);if(tested.length%15===0)console.log("Painted",tested.length);
  if(a.id==='bath_washer'){await page.screenshot({path:'output/bathroom/washer-recolored.png'});await act('undo');assert.equal((await inspect()).rooms[0].items.find(i=>i.id===before.selected).color,null);await act('redo');assert.equal((await inspect()).rooms[0].items.find(i=>i.id===before.selected).color,'#87a9ce');await page.evaluate(id=>window.__homeEditor.select(id),before.selected);await act('palette');await act('color','[data-value=""]');assert.deepEqual(await meshColors(),original);await page.locator('[data-furniture-color]').evaluate(el=>{el.value='#87a9ce';el.dispatchEvent(new Event('change',{bubbles:true}));});}
  if(a.id!=='gaming_desk')await act('store');else await act('deselect');
 }
 const last=(await inspect()).rooms[0].items.find(i=>i.assetId==='bath_toilet');await page.reload();await page.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});assert.equal((await inspect()).rooms[0].items.find(i=>i.id===last.id).color,'#87a9ce');
 await act('panel','[data-panel="storage"]');await act('restore','[data-id="'+last.id+'"]');await act('copy');const copyState=await inspect(),copied=copyState.rooms[0].items.find(i=>i.id===copyState.selected);assert.equal(copied.color,'#87a9ce');
 await page.evaluate(()=>window.advanceTime(0));const warm=await inspect();for(let n=0;n<8;n++){if(!await page.locator('[data-furniture-color]').count())await act('palette');await page.locator('[data-furniture-color]').evaluate((el,color)=>{el.value=color;el.dispatchEvent(new Event('change',{bubbles:true}));},n%2?'#87a9ce':'#ce9ba9');await page.evaluate(()=>window.advanceTime(0));}const after=await inspect();console.log('Resource counts',warm.geometries,after.geometries,warm.textures,after.textures);assert.ok(after.geometries<=warm.geometries+1);assert.equal(after.textures,warm.textures);await page.close();
 assert.deepEqual(errors,[]);await fs.writeFile('output/bathroom/qa-report.json',JSON.stringify({assets:bath.length,bytes,triangles,paintedFurniture:tested.length,tested,feetOnlySeated:true,nestedSupports:true,paintHistoryReloadCopy:true,resourceReuse:true,errors},null,2));console.log('Bathroom geometry, seating-only feet, 90 furniture paint paths, persistence/history/copy and resources passed');
}finally{await browser.close();}
