// Geometry-only bathroom pack. Colors are authored by part, never sampled images.
import fs from 'node:fs/promises';import * as T from 'three';
import {RoundedBoxGeometry} from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import {mergeGeometries,mergeVertices,toCreasedNormals} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {readGeometry,splitParts,compactGeometry,saveGlb} from './asset-geometry.mjs';
import {furniturePaintMaterials} from '../../apps/room3d/furniturePaint.js';
const mat=(name,color)=>{const m=new T.MeshStandardMaterial({color,roughness:.78});m.name=name;return m;};
const m={water:mat('bath-water','#c8d8ce'),shell:mat('bath-shell','#343b36'),accent:mat('bath-accent','#81916b'),cream:mat('bath-cream','#f2f3ed'),ceramic:mat('bath-ceramic','#fafaf5'),pink:mat('bath-towel','#e7ebe2'),metal:mat('bath-metal','#343b36'),dark:mat('bath-rubber','#252c28'),blue:mat('bath-blue','#a8b7a4'),soap:mat('bath-soap','#f2f3ed'),wood:mat('woodLight','#ffffff'),glass:mat('bath-glass','#c9d6c6')};
m.wood.color.setRGB(.8227857351303101,.5972017645835876,.3915724754333496);m.metal.metalness=.45;m.metal.roughness=.35;m.glass.transparent=true;m.glass.opacity=.20;m.glass.depthWrite=false;m.glass.side=T.DoubleSide;
const catalog=JSON.parse(await fs.readFile('public/room3d/catalog.json','utf8')),report=[];
const group=()=>new T.Group(),add=(r,g,material)=>{g.deleteAttribute('uv');g.deleteAttribute('color');const mesh=new T.Mesh(g,material);r.add(mesh);return mesh;};
async function part(r,g,p,material){const raw=await compactGeometry(g,p.ids);return add(r,mergeVertices(toCreasedNormals(raw,Math.PI/2)),material);}
async function load(i){const g=mergeGeometries(await readGeometry('art/jellyfish-home/sources/bathroom-'+i+'-geometry.glb'));return {g,parts:splitParts(g)};}
function box(r,size,pos,material,radius=.008){const g=mergeVertices(new RoundedBoxGeometry(...size,2,radius));g.translate(...pos);return add(r,g,material);}
function roundedPath(x,y,w,h,r,Path=T.Shape){const p=new Path();p.moveTo(x+r,y);p.lineTo(x+w-r,y);p.quadraticCurveTo(x+w,y,x+w,y+r);p.lineTo(x+w,y+h-r);p.quadraticCurveTo(x+w,y+h,x+w-r,y+h);p.lineTo(x+r,y+h);p.quadraticCurveTo(x,y+h,x,y+h-r);p.lineTo(x,y+r);p.quadraticCurveTo(x,y,x+r,y);return p;}
async function emit(id,name,r,width,{height,surface='floor',...extra}={}){
 const buckets=new Map();r.updateMatrixWorld(true);r.traverse(o=>{if(!o.isMesh)return;const key=o.material.name;if(!buckets.has(key))buckets.set(key,{material:o.material,gs:[]});buckets.get(key).gs.push(o.geometry.clone().applyMatrix4(o.matrixWorld));});
 const root=group();for(const {material,gs}of buckets.values())add(root,mergeGeometries(gs),material);
 const bounds=new T.Box3().setFromObject(root),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),sx=width/size.x,sy=height?height/size.y:sx;
 const point=p=>[(p[0]-center.x)*sx,(p[1]-bounds.min.y)*sy,(p[2]-center.z)*sx];root.traverse(o=>{if(o.isMesh)o.geometry.translate(-center.x,-bounds.min.y,-center.z).scale(sx,sy,sx);});size.multiply(new T.Vector3(sx,sy,sx));
 const a={id,name,surface,url:id+'.glb',collection:'bathroom',revision:'bathroom-reference-3',size:size.toArray(),default:[0,.15,0],boxes:[[-size.x/2,0,-size.z/2,size.x/2,size.y,size.z/2]],...extra};a.paintMaterials=furniturePaintMaterials(a,[...buckets.keys()]);
 const ix=catalog.findIndex(v=>v.id===id);if(ix<0)catalog.push(a);else catalog[ix]=a;const bytes=await saveGlb(root,'public/room3d/'+id+'.glb');let triangles=0;root.traverse(o=>{if(o.isMesh)triangles+=o.geometry.index.count/3;});report.push({id,bytes,triangles,groups:buckets.size,size:a.size});return {a,point};
}
// Combined vanity: keep cabinet, basin, taps and upper cupboard registered.
{const {g,parts}=await load(1),r=group();for(const p of parts){const c=p.center,s=p.box.getSize(new T.Vector3());const color=[1895,2018].includes(p.id)?m.blue:[1897,1836,1907].includes(p.id)?m.accent:p.id===1847?m.ceramic:[2087,2102,1534,1864,290,2039,2049,2032].includes(p.id)?m.metal:c.y<-.46?m.wood:s.y<.055&&s.x>.4?m.wood:c.y>.02&&c.y<.14&&Math.abs(c.x)>.13?m.soap:m.cream;await part(r,g,p,color);}box(r,[.27,.014,.19],[-.003,-.199,.033],m.ceramic,.005);await emit('bath_vanity','猫耳洗手台与镜柜',r,1.8,{height:3.35});}
// Storage trolley: towels, bottles, frame and wheels keep distinct colors.
{const {g,parts}=await load(2),r=group();for(const p of parts){const c=p.center,s=p.box.getSize(new T.Vector3());await part(r,g,p,[2089,2197,2030].includes(p.id)?m.accent:p.id===2156?m.cream:c.y<-.41?m.dark:[1640,1939,2061].includes(p.id)?m.pink:p.id===2124?m.cream:c.y>.25&&s.x<.15?m.blue:m.ceramic);}await emit('bath_cart','三层洗浴收纳推车',r,.94,{height:1.85});}
// Stool and bathmat are independent, so the mat does not block furniture placement.
{const {g,parts}=await load(3),stool=group(),rug=group();for(const p of parts){if(p.id===2059)continue;await part(p.id===2042?rug:stool,g,p,p.id===2042?m.pink:p.center.y<-.1?m.cream:m.wood);}
 const shape=roundedPath(-.5,-.210,.43,.372,.035);for(const x of [-.4275,-.3325,-.2375,-.1425])shape.holes.push(roundedPath(x-.015,-.126,.03,.205,.01,T.Path));const seat=mergeVertices(new T.ExtrudeGeometry(shape,{depth:.052,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.006,bevelThickness:.006,curveSegments:5}));seat.rotateX(Math.PI/2);seat.translate(0,.150,0);add(stool,seat,m.accent);
 const st=await emit('bath_stool','圆角沐浴小凳',stool,1.1,{height:.73,category:'seating'});st.a.seats=[{id:'center',label:'沐浴小凳',position:[0,.73,.22],rotation:0}];await emit('bath_mat','小云朵浴室地垫',rug,1.30,{surface:'rug',height:.035,paintMaterials:['bath-towel']});}
{const {g,parts}=await load(4),r=group();for(const p of parts){const c=p.center,s=p.box.getSize(new T.Vector3());await part(r,g,p,[2139,2202].includes(p.id)?m.pink:[1966,2162,2040,2001].includes(p.id)?m.accent:s.y>.65?m.wood:s.x>.3||[1288,2068,2075,2113].includes(p.id)?m.cream:m.metal);}await emit('bath_hamper','猫耳布艺洗衣篮',r,.88,{height:1.42,paintMaterials:['bath-towel']});}
// Tinted panels use plain low-opacity color, no image or costly transmission pass.
{const {g,parts}=await load(5),r=group();for(const p of parts){if([1003,1124].includes(p.id))continue;const c=p.center;await part(r,g,p,[126,1805,611].includes(p.id)?m.glass:[2145,2164,2139].includes(p.id)?m.ceramic:[2178,2176,2172,1171,1957,1590,2016,2151].includes(p.id)?m.shell:[2119,1939,1922,1891,1994].includes(p.id)?m.metal:c.y<-.4?m.cream:p.id===2136?m.cream:m.metal);}await emit('bath_shower','猫耳磨砂淋浴间',r,1.85,{height:3.15,paintMaterials:['bath-shell']});}
{const {g,parts}=await load(6),r=group();for(const p of parts){const c=p.center;await part(r,g,p,[2155,2146,2191,2200].includes(p.id)?m.pink:[2111,2199,1975].includes(p.id)?m.ceramic:[2203,2187,2188,1968,2177].includes(p.id)?m.wood:m.accent);}await emit('bath_towel_rack','原木毛巾梯架',r,1.1,{height:2.25,paintMaterials:['bath-towel']});}
{const {g,parts}=await load(7),r=group();for(const p of parts){const c=p.center,s=p.box.getSize(new T.Vector3());await part(r,g,p,s.x>.1&&s.x<.15&&c.y>.08&&c.y<.34?(c.x<0?m.pink:m.ceramic):[2085,1804,1930,1988].includes(p.id)?m.blue:c.y<-.45?m.wood:s.y>.2&&s.z<.04||p.id===1914?m.accent:s.x<.04&&s.y<.06?m.metal:m.cream);}await emit('bath_linen_cabinet','猫耳毛巾收纳柜',r,1.12,{height:2.65});}
// Rebuild the damaged washer front/body as a closed rounded appliance. Keep
// source feet and the two separate countertop props; no hollow/torn drum pieces.
{const {g,parts}=await load(8),r=group(),towels=group(),bottle=group();for(const p of parts){if([2139,2180].includes(p.id))await part(bottle,g,p,p.id===2180?m.cream:m.blue);else if([1877,2083].includes(p.id))await part(towels,g,p,m.pink);else if([2201,2143,2194,2169].includes(p.id))await part(r,g,p,m.dark);}
 box(r,[.616,.765,.417],[.002,-.080,-.004],m.accent,.028);
 box(r,[.602,.024,.404],[.002,.310,-.004],m.cream,.010);
 box(r,[.568,.142,.020],[.002,.219,.211],m.cream,.014);
 const circle=(radius,depth,x,y,z,material)=>{const geo=new T.CylinderGeometry(radius,radius,depth,40);geo.rotateX(Math.PI/2);geo.translate(x,y,z);return add(r,geo,material);};
 circle(.225,.012,.002,-.105,.210,m.cream);circle(.192,.015,.002,-.105,.223,m.dark);
 const glass=new T.SphereGeometry(.185,40,16);glass.scale(1,1,.115);glass.translate(.002,-.105,.231);add(r,glass,m.blue);
 const ring=new T.TorusGeometry(.206,.025,10,48);ring.translate(.002,-.105,.237);add(r,ring,m.cream);
 box(r,[.030,.113,.028],[.214,-.105,.261],m.cream,.012);
 box(r,[.174,.056,.015],[-.166,.218,.227],m.ceramic,.007);box(r,[.105,.017,.008],[-.167,.218,.239],m.accent,.003);
 circle(.027,.022,.018,.219,.237,m.metal);box(r,[.097,.026,.008],[.170,.228,.227],m.dark,.006);for(const x of [.145,.187])circle(.008,.008,x,.191,.229,m.accent);
 circle(.027,.008,.229,-.370,.209,m.cream);
 const out=await emit('bath_washer','奶油滚筒洗衣机',r,1.34,{height:1.55});const lid=out.point([.002,.322,-.004]);out.a.support={shape:'rect',width:1.18,depth:.82,height:1.55,center:[lid[0],lid[2]]};await emit('bath_folded_towels','叠好的浴巾',towels,.58,{surface:'tabletop',paintMaterials:['bath-towel']});await emit('bath_detergent','小瓶洗衣液',bottle,.28,{surface:'tabletop',paintMaterials:['bath-blue']});}
// Tub: keep the inside ceramic, color the outer bowl; smooth the supplied contour.
{const {g,parts}=await load(9),r=group(),tray=group(),soap=group();for(const p of parts){if([2210,1167,2154,2211,1649,1702,2170,2034].includes(p.id)){const board=[2210,1167].includes(p.id);await part(board?tray:soap,g,p,board?m.wood:p.id===2154?m.ceramic:p.id===2034?m.pink:[1649,1702,2170].includes(p.id)?m.metal:m.soap);continue;}if(p.id!==2192){await part(r,g,p,m.metal);continue;}const pos=g.attributes.position,a=new T.Vector3(),b=new T.Vector3(),c=new T.Vector3(),n=new T.Vector3(),center=new T.Vector3(),inside=[],outside=[],base=[];for(let t=0;t<p.ids.length;t+=3){a.fromBufferAttribute(pos,p.ids[t]);b.fromBufferAttribute(pos,p.ids[t+1]);c.fromBufferAttribute(pos,p.ids[t+2]);center.copy(a).add(b).add(c).multiplyScalar(1/3);n.subVectors(b,a).cross(new T.Vector3().subVectors(c,a)).normalize();const bucket=center.y<-.28?base:n.y>.45||n.x*center.x+n.z*(center.z-.015)<-.012?inside:outside;bucket.push(...p.ids.slice(t,t+3));}for(const [ids,color]of [[inside,m.ceramic],[outside,m.accent],[base,m.cream]])if(ids.length)await part(r,g,{ids},color);}
 const water=new T.CircleGeometry(1,40);water.rotateX(-Math.PI/2);water.scale(.40,1,.155);water.translate(0,-.06,.015);add(r,water,m.water);
 const tub=await emit('bath_tub','猫耳独立浴缸',r,2.90);const rest=tub.point([-.211,.060,.015]);const bowl=parts.find(p=>p.id===2192),bodyBox=[...tub.point(bowl.box.min.toArray()),...tub.point(bowl.box.max.toArray())],top=bodyBox[4];bodyBox[4]=rest[1]+.03;tub.a.boxes=[bodyBox,...[[-.5,-.39],[.39,.5]].map(([lo,hi])=>[tub.point([lo,0,0])[0],bodyBox[4],bodyBox[2],tub.point([hi,0,0])[0],top,bodyBox[5]]),...parts.filter(p=>![2192,2210,1167,2154,2211,1649,1702,2170,2034].includes(p.id)).map(p=>[...tub.point(p.box.min.toArray()),...tub.point(p.box.max.toArray())])];tub.a.support={shape:'rect',width:.42,depth:1.51,height:rest[1],center:[rest[0],rest[2]]};const board=await emit('bath_tray','原木浴缸置物板',tray,.35,{surface:'tabletop',contact:{width:.32,depth:1.42}});board.a.support={shape:'rect',width:.33,depth:1.47,height:board.a.size[1]};await emit('bath_soap','香皂与洗浴小瓶',soap,.30,{surface:'tabletop',paintMaterials:['bath-soap']});}
{const {g,parts}=await load(10),r=group();for(const p of parts)await part(r,g,p,[2100,2166].includes(p.id)?m.accent:[2185,2200,1981,2157].includes(p.id)?m.metal:m.ceramic);await emit('bath_toilet','猫耳陶瓷马桶',r,.95,{height:1.65});}
await fs.writeFile('public/room3d/catalog.json',JSON.stringify(catalog,null,2)+'\n');await fs.mkdir('output/bathroom',{recursive:true});await fs.writeFile('output/bathroom/assets-report.json',JSON.stringify(report,null,2));console.log(report);
