// Geometry-only bedroom pack. Colors are authored by part, never sampled images.
import fs from 'node:fs/promises';import * as T from 'three';
import {RoundedBoxGeometry} from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import {mergeGeometries,mergeVertices,toCreasedNormals} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {readGeometry,splitParts,compactGeometry,saveGlb} from './asset-geometry.mjs';
import {furniturePaintMaterials} from '../../apps/room3d/furniturePaint.js';
const mat=(name,color)=>{const m=new T.MeshStandardMaterial({color,roughness:.78});m.name=name;return m;};
const m={accent:mat('bed-accent','#b9acd1'),cream:mat('bed-cream','#f1e9dc'),ceramic:mat('bed-ceramic','#fff7eb'),pink:mat('bed-towel','#dec2ca'),metal:mat('bed-metal','#a8afb2'),dark:mat('bed-rubber','#565b65'),blue:mat('bed-blue','#9cbec9'),soap:mat('bed-soap','#e4d3a1'),wood:mat('woodLight','#ffffff'),glass:mat('bed-glass','#b5d5db')};
m.wood.color.setRGB(.8227857351303101,.5972017645835876,.3915724754333496);m.metal.metalness=.45;m.metal.roughness=.35;m.glass.transparent=true;m.glass.opacity=.20;m.glass.depthWrite=false;m.glass.side=T.DoubleSide;
m.shark=mat('shark-blue','#7093a6');
const catalog=JSON.parse(await fs.readFile('public/room3d/catalog.json','utf8')),report=[];
const group=()=>new T.Group(),add=(r,g,material)=>{g.deleteAttribute('uv');g.deleteAttribute('color');const mesh=new T.Mesh(g,material);r.add(mesh);return mesh;};
async function part(r,g,p,material){const raw=await compactGeometry(g,p.ids);return add(r,mergeVertices(toCreasedNormals(raw,Math.PI/2)),material);}
async function load(i){const g=mergeGeometries(await readGeometry('art/jellyfish-home/sources/bedroom-'+i+'-geometry.glb'));return {g,parts:splitParts(g)};}
function box(r,size,pos,material,radius=.008){const g=mergeVertices(new RoundedBoxGeometry(...size,2,radius));g.translate(...pos);return add(r,g,material);}
function roundedPath(x,y,w,h,r,Path=T.Shape){const p=new Path();p.moveTo(x+r,y);p.lineTo(x+w-r,y);p.quadraticCurveTo(x+w,y,x+w,y+r);p.lineTo(x+w,y+h-r);p.quadraticCurveTo(x+w,y+h,x+w-r,y+h);p.lineTo(x+r,y+h);p.quadraticCurveTo(x,y+h,x,y+h-r);p.lineTo(x,y+r);p.quadraticCurveTo(x,y,x+r,y);return p;}
async function emit(id,name,r,width,{height,depth,surface='floor',...extra}={}){
 const buckets=new Map();r.updateMatrixWorld(true);r.traverse(o=>{if(!o.isMesh)return;const key=o.material.name;if(!buckets.has(key))buckets.set(key,{material:o.material,gs:[]});buckets.get(key).gs.push(o.geometry.clone().applyMatrix4(o.matrixWorld));});
 const root=group();for(const {material,gs}of buckets.values())add(root,mergeGeometries(gs),material);
 const bounds=new T.Box3().setFromObject(root),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),sx=width/size.x,sy=height?height/size.y:sx,sz=depth?depth/size.z:sx;
 const point=p=>[(p[0]-center.x)*sx,(p[1]-bounds.min.y)*sy,(p[2]-center.z)*sz];root.traverse(o=>{if(o.isMesh)o.geometry.translate(-center.x,-bounds.min.y,-center.z).scale(sx,sy,sz);});size.multiply(new T.Vector3(sx,sy,sz));
 const a={id,name,surface,url:id+'.glb',collection:'bedroom',size:size.toArray(),default:[0,.15,0],boxes:[[-size.x/2,0,-size.z/2,size.x/2,size.y,size.z/2]],...extra};a.paintMaterials=furniturePaintMaterials(a,[...buckets.keys()]);
 const ix=catalog.findIndex(v=>v.id===id);if(ix<0)catalog.push(a);else catalog[ix]=a;const bytes=await saveGlb(root,'public/room3d/'+id+'.glb');let triangles=0;root.traverse(o=>{if(o.isMesh)triangles+=o.geometry.index.count/3;});report.push({id,bytes,triangles,groups:buckets.size,size:a.size});return {a,point};
}
function ellipse(r,size,pos,material){const g=new T.CircleGeometry(1,48);g.scale(size[0],size[1],1);g.translate(...pos);return add(r,g,material);}
const put=async(r,g,p,color)=>part(r,g,p,color),is=(p,ids)=>ids.includes(p.id);
const paint={paintMaterials:['bed-accent']};
function support(out,raw,width,depth){const p=out.point(raw);out.a.support={shape:'rect',width,depth,height:p[1],center:[p[0],p[2]]};}
// Vanity: separate stool and cosmetics; mirror remains registered with the desk.
{const {g,parts}=await load(1),r=group(),stool=group(),brushes=group(),perfume=group(),cup=group();
 for(const p of parts){const c=p.center;if(c.y<-.18&&Math.abs(c.x)<.18)await put(stool,g,p,p.id===2143?m.accent:m.wood);
 else if(c.y>.023&&c.y<.18&&c.x>.25)await put(perfume,g,p,p.id===2004?m.pink:m.metal);
 else if(c.y>.023&&c.y<.15&&c.x>.10)await put(brushes,g,p,p.id===1991?m.accent:m.wood);
 else if(c.y>.023&&c.y<.10&&c.x<-.1&&c.z>-.13)await put(cup,g,p,m.cream);
 else await put(r,g,p,p.id===1908?m.cream:[1655,1678,544].includes(p.id)?m.accent:c.y<-.15?m.wood:m.cream);}
 ellipse(r,[.165,.203],[-.044,.268,-.165],m.blue);const out=await emit('bedroom_vanity','猫耳梳妆台',r,2.55,{height:2.9,...paint});support(out,[0,.024,-.018],2.20,.82);out.a.chairSlots=[{id:'front',position:[0,0,.95],rotation:180}];
 const seat=await emit('bedroom_stool','梳妆圆凳',stool,.80,{height:.64,category:'seating',...paint});seat.a.seats=[{id:'center',label:'圆凳',position:[0,.64,.12],rotation:0}];
 await emit('bedroom_brushes','梳妆刷收纳盒',brushes,.34,{surface:'tabletop',...paint});await emit('bedroom_perfume','蝴蝶结香水瓶',perfume,.25,{surface:'tabletop',paintMaterials:['bed-towel']});await emit('bedroom_brush_cup','小梳妆杯',cup,.30,{surface:'tabletop',paintMaterials:['bed-cream']});}
{const {g,parts}=await load(2),r=group();for(const p of parts)await put(r,g,p,[2157,2141].includes(p.id)?m.accent:p.center.y<-.1?m.wood:m.cream);const out=await emit('bedroom_bench','猫耳软垫床尾凳',r,3.7,{height:1.15,...paint});const y=out.point([0,.170,0])[1];out.a.seats=[{id:'left',label:'左边',position:[-.94,y,.30],rotation:0},{id:'right',label:'右边',position:[.94,y,.30],rotation:0}];}
{const {g,parts}=await load(3),lamp=group(),shark=group(),jelly=group(),turtle=group();for(const p of parts){const c=p.center;if(c.x<-.3)await put(lamp,g,p,[2145,1379,2181].includes(p.id)?m.accent:c.y<-.25?m.wood:m.metal);else if(c.x<0){
 if(p.id===2151){
  const body=mergeVertices(toCreasedNormals(await compactGeometry(g,p.ids),Math.PI/2)),pos=body.attributes.position,idx=body.index,blue=[],belly=[];
  for(let k=0;k<idx.count;k+=3){const ids=[idx.getX(k),idx.getX(k+1),idx.getX(k+2)],y=ids.reduce((sum,i)=>sum+pos.getY(i),0)/3;(y<-.248?belly:blue).push(...ids);}
  for(const [ids,material] of [[blue,m.shark],[belly,m.cream]]){const patch=body.clone();patch.setIndex(ids);add(shark,patch,material);}
 }else await put(shark,g,p,[2032,2080].includes(p.id)?m.cream:m.shark);
}else if(c.x<.24)await put(jelly,g,p,p.id===2058?m.accent:m.cream);else await put(turtle,g,p,p.id===2169?m.blue:m.cream);}
 await emit('bedroom_floor_lamp','猫耳落地灯',lamp,.63,{height:2.10,...paint});await emit('bedroom_rabbit','软绵鲨鱼玩偶',shark,.72,{height:.63,depth:.78,holdable:true,category:'plush',revision:'shark-blue-1',paintMaterials:['shark-blue']});await emit('bedroom_jelly','小水母玩偶',jelly,.74,{holdable:true,category:'plush',...paint});await emit('bedroom_turtle','小海龟玩偶',turtle,.70,{depth:.84,holdable:true,category:'plush',paintMaterials:['bed-blue']});}
{const {g,parts}=await load(4),r=group();for(const p of parts){const c=p.center,s=p.box.getSize(new T.Vector3());if(c.z>.15&&c.y>-.27&&c.y<.39)continue;await put(r,g,p,c.y<-.39?m.wood:s.x<.045&&s.y<.07?m.metal:c.z>.1&&c.y<.36?m.accent:m.cream);}for(const x of [-.158,.158]){box(r,[.303,.646,.025],[x,.062,.16],m.accent,.009);box(r,[.252,.585,.006],[x,.062,.176],m.accent,.007);const knob=new T.SphereGeometry(.012,12,8);knob.translate(x<0?-.038:.038,.062,.193);add(r,knob,m.metal);}await emit('bedroom_wardrobe','猫耳双门衣柜',r,2.0,{height:3.15,...paint});}
// The horizontal beds have extra depth for the chibi head; guard geometry stays intact.
{const {g,parts}=await load(5),r=group();for(const p of parts){const c=p.center,s=p.box.getSize(new T.Vector3());await put(r,g,p,[2042,2072].includes(p.id)?m.accent:s.x>.25&&s.y<.10?m.pink:c.y<-.40?m.wood:Math.abs(c.x)>.43?m.cream:m.wood);}const out=await emit('bedroom_bunk','猫耳上下铺',r,4.0,{height:3.8,depth:2.15,...paint});out.a.beds=[{id:'lower',label:'下铺',position:out.point([-.05,-.20,0]),rotation:90},{id:'upper',label:'上铺',position:out.point([-.05,.34,0]),rotation:90}];}
{const {g,parts}=await load(6),r=group(),chair=group(),stationery=group();const chairIds=[2130,2090,2012,2154,1922,1505,2005,1844,1394];
 for(const p of parts){const c=p.center,s=p.box.getSize(new T.Vector3());if(is(p,chairIds))await put(chair,g,p,[2130,2090].includes(p.id)?m.accent:m.wood);else if(c.y>-.115&&c.y<0&&c.x>-.36&&c.x<.26)await put(stationery,g,p,[2174,1923,2189].includes(p.id)?m.accent:m.wood);else await put(r,g,p,[1834,1839].includes(p.id)?m.cream:[1780,2177,2071].includes(p.id)?m.accent:c.y<-.42||s.y>.6?m.wood:c.z>.06&&c.y<-.13&&c.x>.04?m.accent:m.cream);}
 const out=await emit('bedroom_loft','猫耳书桌高架床',r,4.2,{height:4.2,depth:2.20,...paint});out.a.beds=[{id:'upper',label:'上铺',position:out.point([-.045,.32,0]),rotation:90}];support(out,[-.16,-.115,-.02],1.6,1.10);
 // Keep the usable desk/chair cavity open; legs, desk and upper bed still collide.
 const w=out.a.size[0]/2,d=out.a.size[2]/2,desk=out.point([0,-.115,0])[1],upper=out.point([0,.22,0])[1];out.a.boxes=[[-w,0,-d,-w+.23,4.2,d],[w-.23,0,-d,w,4.2,d],[-w,upper,-d,w,4.2,d],[-w+.2,desk-.12,-d,w-.2,desk,d-.32],[.23,0,-d,w-.25,desk,d-.30]];
 out.a.chairSlots=[{id:'desk',position:[-.60,0,1.42],rotation:180}];chair.rotation.y=Math.PI;const seat=await emit('bedroom_desk_chair','原木书桌椅',chair,.90,{height:1.25,...paint});seat.a.seats=[{id:'center',label:'书桌椅',position:[0,.65,.20],rotation:0}];await emit('bedroom_stationery','笔筒与桌边文具',stationery,.58,{surface:'tabletop',...paint});}
{const {g,parts}=await load(7),r=group(),plush=group();for(const p of parts){if(is(p,[2112,2071]))await put(plush,g,p,m.pink);else await put(r,g,p,[1814,2088].includes(p.id)?m.accent:p.id===2075||p.id===2109?m.cream:p.center.y<-.12?m.wood:m.cream);}const out=await emit('bedroom_single_bed','猫耳单人床',r,2.10,{height:1.85,depth:3.45,...paint});out.a.beds=[{id:'center',label:'枕边',position:out.point([0,.055,-.025]),rotation:0}];await emit('bedroom_pillow_plush','软绵抱枕玩偶',plush,.66,{holdable:true,category:'plush',paintMaterials:['bed-towel']});}
{const {g,parts}=await load(8),r=group();for(const p of parts)await put(r,g,p,p.id===2156?m.accent:[2169,2175,2013,2163].includes(p.id)?m.cream:p.id===2174?m.metal:p.center.y<-.13?m.wood:m.cream);const out=await emit('bedroom_double_bed','猫耳双人床',r,3.65,{height:2.02,depth:3.65,...paint});out.a.beds=[{id:'left',label:'左边',position:out.point([-.22,.055,-.02]),rotation:0},{id:'right',label:'右边',position:out.point([.22,.055,-.02]),rotation:0}];}
{const {g,parts}=await load(9),r=group(),lamp=group(),clock=group();for(const p of parts){const c=p.center;if(c.y>.11&&c.x<-.02&&c.x>-.24&&c.z>-.12)await put(lamp,g,p,[2050,2029,1600].includes(p.id)?m.accent:m.cream);else if(c.y>.11&&c.x>0&&c.x<.23&&c.z>-.12)await put(clock,g,p,p.id===2055?m.pink:m.metal);else await put(r,g,p,[1821,1923].includes(p.id)?m.metal:[2026,2011].includes(p.id)?m.accent:c.y<-.40?m.wood:m.cream);}const out=await emit('bedroom_nightstand','猫耳双抽床头柜',r,1.0,{height:1.08,...paint});support(out,[0,.163,.025],.82,.55);await emit('bedroom_table_lamp','猫耳床头灯',lamp,.39,{surface:'tabletop',...paint});await emit('bedroom_alarm','奶油双铃闹钟',clock,.30,{surface:'tabletop',paintMaterials:['bed-towel']});}
{const {g,parts}=await load(10),r=group(),mirror=group(),jewels=group(),bottle=group();for(const p of parts){const c=p.center,s=p.box.getSize(new T.Vector3());if(c.y>.20&&c.x>-.02&&c.x<.24&&c.z>-.12)await put(mirror,g,p,p.id===2054?m.cream:m.cream);else if(c.y>.20&&c.x>.24&&c.x<.4)await put(bottle,g,p,p.id===1987?m.pink:m.metal);else if(c.y>.20&&c.x<-.08&&c.x>-.3)await put(jewels,g,p,m.accent);else await put(r,g,p,c.y<-.37?m.wood:c.z>.12&&c.y<.15?(s.x<.1?m.metal:m.accent):m.cream);}const out=await emit('bedroom_dresser','猫耳六抽斗柜',r,2.10,{height:1.65,...paint});support(out,[0,.199,.02],1.85,.55);ellipse(mirror,[.086,.088],[.105,.342,.004],m.blue);await emit('bedroom_mirror','猫耳台式镜',mirror,.44,{surface:'tabletop',paintMaterials:['bed-cream']});await emit('bedroom_jewelry_box','小小首饰盒',jewels,.38,{surface:'tabletop',...paint});await emit('bedroom_scent','桌边香氛瓶',bottle,.25,{surface:'tabletop',paintMaterials:['bed-towel']});}
await fs.writeFile('public/room3d/catalog.json',JSON.stringify(catalog,null,2)+'\n');await fs.mkdir('output/bedroom',{recursive:true});await fs.writeFile('output/bedroom/assets-report.json',JSON.stringify(report,null,2));console.log(report.map(a=>[a.id,a.triangles,a.bytes,a.size]));
