import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=await import('file:///C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader']});await fs.mkdir('output/bedroom',{recursive:true});const errors=[];
const catalog=JSON.parse(await fs.readFile('public/room3d/catalog.json','utf8'));
async function setup(url,mobile=false){const p=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1100,height:850},isMobile:mobile,hasTouch:mobile});p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.goto('http://127.0.0.1:5174/test/fixtures/room3d-bedroom.html'+url);await p.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});const state=()=>p.evaluate(()=>window.__homeEditor.inspect()),act=async(a,q='')=>{if(a==='panel'&&(await state()).panel===q.match(/data-panel="([^"]+)/)?.[1])return;await p.locator('[data-action="'+a+'"]'+q).first().click();};const advance=ms=>p.evaluate(ms=>window.advanceTime(ms),ms),limbs=()=>p.evaluate(()=>{const out=[];window.__visitor.root.traverse(o=>{if(o.name.startsWith('chibi-action-'))out.push({name:o.name,visible:o.visible,scale:o.scale.toArray()});});return out;});return {p,state,act,advance,limbs};}
try{
 let sleepPositions=0;
 for(const a of catalog.filter(a=>a.beds)){
  const {p,state,act,advance,limbs}=await setup('?bed='+a.id);assert.equal((await state()).rooms[0].items.length,15);
  for(const b of a.beds){await act('panel','[data-panel="chibi"]');await act('chibi-bed','[data-id="'+a.id+'"][data-seat="'+b.id+'"]');await advance(600);let s=await state();assert.equal(s.chibiPosture,'lying');assert.equal(s.chibiMotion,'sleep');assert.equal(s.chibiSeat.seatId,b.id);assert.equal((await limbs()).filter(o=>o.name.includes('foot')&&o.visible).length,0);await act('panel','[data-panel="chibi"]');await act('chibi-view');await p.screenshot({path:'output/bedroom/sleep-'+a.id+'-'+b.id+'.png'});sleepPositions++;}
  await p.evaluate(id=>window.__homeEditor.select(id),a.id);await act('store');assert.equal((await state()).chibiSeat,null);await act('undo');await act('panel','[data-panel="chibi"]');await act('chibi-bed','[data-id="'+a.id+'"]');await act('panel','[data-panel="chibi"]');await act('chibi-stand');assert.equal((await state()).chibiPosture,'standing');await p.close();console.log('Bed',a.id);
 }
 const {p,state,act,advance,limbs}=await setup('?empty');
 const add=async id=>{await act('panel','[data-panel="furniture"]');await act('category','[data-value="all"]');await act('add-item','[data-id="'+id+'"]');return (await state()).selected;};
 const bench=await add('bedroom_bench'),dolls=[];for(const a of catalog.filter(a=>a.holdable))dolls.push({a,id:await add(a.id)});
 await act('panel','[data-panel="furniture"]');await act('catalog-mode','[data-value="use"]');await act('category','[data-value="decor"]');assert.equal(await p.locator('.h3-asset .h3-action-badge[aria-label="可互动：抱抱"]').count(),4);await act('catalog-mode','[data-value="room"]');await act('category','[data-value="bedroom"]');assert.equal(await p.locator('.h3-asset[data-id^="bedroom_"]').count(),25);
 const meshState=()=>p.evaluate(()=>{const r=window.__visitor.root.parent,g=r.getObjectByName('held-plush'),out=[];r.parent.traverse(o=>{if(o.userData.itemId&&o.userData.assetId)out.push({id:o.userData.itemId,visible:o.visible});});const mats=[];g.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])mats.push([m.name,m.color.getHexString()]);});return {count:g.children.length,scale:g.children[0]?.scale.toArray(),mats,originals:out};});
 for(const {a,id} of dolls){const before=JSON.stringify((await state()).rooms);await act('panel','[data-panel="chibi"]');await act('chibi-hug','[data-id="'+id+'"]');await advance(700);assert.equal((await state()).chibiHeldPlush.itemId,id);assert.equal((await state()).chibiMotion,'hug');assert.equal((await limbs()).filter(o=>o.visible).length,2);const m=await meshState();assert.equal(m.count,1);assert.ok(m.scale.every(v=>v===m.scale[0]));assert.ok(m.originals.filter(o=>o.id===id).every(o=>!o.visible));assert.equal(JSON.stringify((await state()).rooms),before);await act('panel','[data-panel="chibi"]');await act('chibi-view');await p.screenshot({path:'output/bedroom/hug-'+a.id+'.png'});
  await act('panel','[data-panel="chibi"]');await act('plush-put-back');assert.equal((await meshState()).count,0);assert.ok((await meshState()).originals.filter(o=>o.id===id).every(o=>o.visible));assert.equal(JSON.stringify((await state()).rooms),before);
 }
 const doll=dolls[0];await act('panel','[data-panel="chibi"]');await act('chibi-sit','[data-id="'+bench+'"]');await act('panel','[data-panel="chibi"]');await act('chibi-hug','[data-id="'+doll.id+'"]');await advance(800);assert.equal((await state()).chibiPosture,'seated');assert.equal((await limbs()).filter(o=>o.visible).length,4);await act('panel','[data-panel="chibi"]');await act('chibi-view');await p.screenshot({path:'output/bedroom/seated-hug.png'});
 // Instance color persists while held and never changes the source geometry.
 await p.evaluate(id=>window.__homeEditor.select(id),doll.id);await act('palette');await p.locator('[data-furniture-color]').fill('#d39cae');await p.locator('[data-furniture-color]').dispatchEvent('change');await advance(0);assert.ok((await meshState()).mats.filter(([n])=>doll.a.paintMaterials.includes(n)).every(([,v])=>v==='d39cae'));await act('store');assert.equal((await state()).chibiHeldPlush,null);await act('undo');await act('panel','[data-panel="chibi"]');await act('chibi-hug','[data-id="'+doll.id+'"]');await advance(0);let warm=await state();for(let n=0;n<8;n++){await act('panel','[data-panel="chibi"]');await act('plush-put-back');await act('chibi-hug','[data-id="'+doll.id+'"]');await advance(0);}let after=await state();assert.equal(after.geometries,warm.geometries);assert.equal(after.textures,warm.textures);
 await act('panel','[data-panel="chibi"]');await act('chibi-motion','[data-value="wave-calm"]');assert.equal((await state()).chibiHeldPlush,null);await act('chibi-stand');await act('chibi-hug','[data-id="'+doll.id+'"]');await p.reload();await p.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});assert.equal((await state()).chibiHeldPlush,null);assert.equal((await state()).rooms[0].items.find(i=>i.id===doll.id).color,'#d39cae');await p.close();
 const mobile=await setup('',true);await mobile.act('panel','[data-panel="chibi"]');await mobile.act('chibi-hug');await mobile.advance(700);assert.equal((await mobile.limbs()).filter(o=>o.visible).length,2);await mobile.act('panel','[data-panel="chibi"]');await mobile.act('chibi-view');await mobile.p.screenshot({path:'output/bedroom/mobile-hug.png'});await mobile.p.close();assert.deepEqual(errors,[]);
 await fs.writeFile('output/bedroom/qa-report.json',JSON.stringify({sleepPositions,dolls:dolls.length,seatedHug:true,originalPositionPreserved:true,colorStorageUndoReload:true,resourceStable:true,mobile:true,errors},null,2));console.log('Bedroom sleep, hugs, storage, colors, resource reuse and mobile passed');
}finally{await browser.close();}
