import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=await import('file:///C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader']});await fs.mkdir('output/room-camera',{recursive:true});const errors=[];
async function setup(mobile=false){const p=await browser.newPage({viewport:mobile?{width:390,height:844}:{width:1100,height:850},hasTouch:mobile,isMobile:mobile});p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://127.0.0.1:5174/test/fixtures/room3d-bedroom.html?empty',{waitUntil:'domcontentloaded',timeout:90000});await p.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});const state=()=>p.evaluate(()=>window.__homeEditor.inspect()),click=(a,q='')=>p.locator('[data-action="'+a+'"]'+q).first().click(),project=v=>p.evaluate(v=>window.__homeEditor.projectPoint(v),v);await p.evaluate(()=>window.advanceTime(0));return {p,state,click,project};}
const near=(a,b)=>a.every((v,i)=>Math.abs(v-b[i])<.001),offset=s=>s.cameraPosition.map((v,i)=>v-s.cameraTarget[i]);
try{
const {p,state,click,project}=await setup();let initial=await state(),point=await project([initial.chibiPosition[0],initial.chibiPosition[1]+1.35,initial.chibiPosition[2]]);
await p.mouse.click(point.x,point.y);assert.equal((await state()).walking,false);await p.waitForTimeout(450);await p.mouse.dblclick(point.x,point.y,{delay:100});let focused=await state();assert.ok(focused.zoom>initial.zoom);assert.equal(focused.walking,false);assert.deepEqual(focused.chibiPosition,initial.chibiPosition);await p.screenshot({path:'output/room-camera/focused.png'});
await p.mouse.move(180,400);await p.mouse.down({button:'right'});await p.mouse.move(260,455,{steps:10});await p.mouse.up({button:'right'});let pan=await state();assert.ok(!near(pan.cameraTarget,focused.cameraTarget));assert.ok(near(offset(pan),offset(focused)));assert.equal(pan.zoom,focused.zoom);assert.equal(pan.walking,false);await p.screenshot({path:'output/room-camera/panned.png'});
await p.mouse.move(180,400);await p.mouse.down();await p.mouse.move(270,430,{steps:8});await p.mouse.up();assert.ok(!near(offset(await state()),offset(pan)));assert.ok(near((await state()).cameraTarget,pan.cameraTarget));
await click('panel','[data-panel="chibi"]');await click('room-view');await click('panel','[data-panel="furniture"]');await click('add-item','[data-id="table"]');const placed=await state(),id=placed.selected;point=await p.evaluate(id=>window.__homeEditor.projectItem(id),id);await p.mouse.move(point.x,point.y);await p.mouse.down();await p.mouse.move(point.x+55,point.y+15,{steps:10});await p.mouse.up();let moved=await state();assert.ok(near(moved.cameraTarget,placed.cameraTarget));const before=placed.rooms[0].items.find(i=>i.id===id),after=moved.rooms[0].items.find(i=>i.id===id);assert.ok(before.x!==after.x||before.z!==after.z,moved.message);await click('undo');assert.deepEqual((await state()).rooms[0].items.find(i=>i.id===id),before);
await p.close();
const mobile=await setup(true),mp=mobile.p,cdp=await mp.context().newCDPSession(mp);let start=await mobile.state();point=await mobile.project([start.chibiPosition[0],start.chibiPosition[1]+1.35,start.chibiPosition[2]]);await mp.touchscreen.tap(point.x,point.y);await mp.waitForTimeout(100);await mp.touchscreen.tap(point.x,point.y);const mf=await mobile.state();assert.ok(mf.zoom>start.zoom);assert.equal(mf.walking,false);await mp.screenshot({path:'output/room-camera/mobile-focused.png'});
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:70,y:360,id:1}]});for(let k=1;k<=8;k++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:70+k*8,y:360+k*4,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const mt=await mobile.state();assert.ok(near(mt.cameraTarget,mf.cameraTarget));assert.ok(!near(offset(mt),offset(mf)));assert.equal(mt.walking,false);await mp.screenshot({path:'output/room-camera/mobile-panned.png'});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:90,y:350,id:1},{x:210,y:350,id:2}]});for(let k=1;k<=6;k++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:90+k*5,y:350+k*5,id:1},{x:210+k*5,y:350+k*5,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const two=await mobile.state();assert.ok(!near(two.cameraTarget,mt.cameraTarget));assert.ok(near(offset(two),offset(mt)));assert.equal(two.zoom,mt.zoom);assert.equal(two.walking,false);await mp.screenshot({path:'output/room-camera/mobile-two-pan.png'});
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:80,y:350,id:1},{x:280,y:350,id:2}]});for(let k=1;k<=6;k++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:80+k*8,y:350,id:1},{x:280-k*8,y:350,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const pinch=await mobile.state();assert.ok(pinch.zoom<two.zoom);assert.ok(near(offset(pinch),offset(two)));assert.equal(pinch.walking,false);await mp.screenshot({path:'output/room-camera/mobile-pinch.png'});await mp.close();assert.deepEqual(errors,[]);await fs.writeFile('output/room-camera/report.json',JSON.stringify({desktopFocus:focused.zoom,touchFocus:mf.zoom,pan:true,furnitureDragUndo:true,leftRotate:true,touchTwoPanPinch:true,errors},null,2));console.log('Desktop/touch double tap, center zoom, right pan, left rotation, one-finger rotation, two-finger pan/pinch, selected furniture drag/undo passed');
}finally{await browser.close();}
