import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {ROOM_CATEGORIES,USE_CATEGORIES,matchesFurniture,furnitureActions} from '../../apps/room3d/furnitureCatalog.js';
const catalog=JSON.parse(await fs.readFile('public/room3d/catalog.json','utf8'));
const {chromium}=await import('file:///C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader']});const errors=[];await fs.mkdir('output/furniture-catalog',{recursive:true});
try{
 const p=await browser.newPage({viewport:{width:1100,height:850}});p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto('http://127.0.0.1:5174/test/fixtures/room3d-finishes.html');await p.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});const click=(a,q='')=>p.locator('[data-action="'+a+'"]'+q).first().click(),state=()=>p.evaluate(()=>window.__homeEditor.inspect());const before=await state();
 await click('panel','[data-panel="furniture"]');
 for(const [mode,categories]of [['room',ROOM_CATEGORIES],['use',USE_CATEGORIES]]){await click('catalog-mode','[data-value="'+mode+'"]');assert.equal(await p.locator('[data-action="category"]').count(),Object.keys(categories).length+1);for(const key of ['all',...Object.keys(categories)]){await click('category','[data-value="'+key+'"]');const ids=await p.locator('.h3-asset').evaluateAll(es=>es.map(e=>e.dataset.id));assert.deepEqual(ids,catalog.filter(a=>matchesFurniture(a,mode,key)).map(a=>a.id));if(!ids.length)assert.ok(await p.getByText('这个分类暂时还没有家具。').isVisible());} }
 await click('category','[data-value="all"]');const cards=await p.locator('.h3-asset').evaluateAll(es=>es.map(e=>({id:e.dataset.id,badge:!!e.querySelector('.h3-action-badge'),title:e.title})));for(const card of cards)assert.equal(card.badge,furnitureActions(catalog.find(a=>a.id===card.id)).length>0,card.id);assert.deepEqual((await state()).rooms,before.rooms);
 await click('category','[data-value="decor"]');await p.screenshot({path:'output/furniture-catalog/decor-badges.png'});await p.locator('[data-id="bedroom_rabbit"]').scrollIntoViewIfNeeded();await p.screenshot({path:'output/furniture-catalog/action-badges.png'});await click('add-item','[data-id="bedroom_rabbit"]');const selected=await state();assert.equal(selected.rooms[0].items.find(i=>i.id===selected.selected).assetId,'bedroom_rabbit');assert.match(await p.locator('.h3-action-detail').innerText(),/抱抱/);await click('store');await click('panel','[data-panel="storage"]');assert.ok(await p.locator('[data-id="'+selected.selected+'"] .h3-action-badge').isVisible());await click('restore','[data-id="'+selected.selected+'"]');assert.equal((await state()).rooms[0].items.find(i=>i.id===selected.selected).stored,false);
 await click('panel','[data-panel="furniture"]');await click('catalog-mode','[data-value="room"]');await click('category','[data-value="living"]');assert.ok(await p.locator('[data-id="small_television"]').isVisible());await p.screenshot({path:'output/furniture-catalog/living.png'});
 await click('category','[data-value="gaming"]');assert.equal(await p.locator('[data-action="gaming-preset"]').count(),4);await click('category','[data-value="kitchen"]');assert.equal(await p.locator('[data-action="dining-preset"]').count(),1);
 await p.setViewportSize({width:390,height:844});await click('catalog-mode','[data-value="use"]');await p.locator('[data-catalog-category]').selectOption('seating');await p.screenshot({path:'output/furniture-catalog/mobile-use.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.locator('[data-catalog-category]').selectOption('outdoor');await p.screenshot({path:'output/furniture-catalog/mobile-empty.png'});await click('panel','[data-panel="building"]');assert.ok(await p.getByRole('heading',{name:'墙体与房间'}).isVisible());assert.deepEqual(errors,[]);console.log('All five room / fourteen use filters, badges, placement/storage/restore, presets, building and mobile passed');await fs.writeFile('output/furniture-catalog/report.json',JSON.stringify({rooms:5,uses:14,cards:cards.length,interactive:cards.filter(c=>c.badge).length,errors},null,2));
}finally{await browser.close();}
