import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=await import(process.env.ROOM3D_PLAYWRIGHT_MODULE||'file:///C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader']});await fs.mkdir('output/furniture-docking',{recursive:true});const errors=[];
try{
 const page=await browser.newPage({viewport:{width:1100,height:850}});page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('http://127.0.0.1:5174/test/fixtures/room3d-docking.html');await page.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});
 const inspect=()=>page.evaluate(()=>window.__homeEditor.inspect()),click=(a,q='')=>page.locator(`[data-action="${a}"]${q}`).click(),select=id=>page.evaluate(id=>window.__homeEditor.select(id),id);
 const initial=await inspect(),desk=initial.rooms[0].items.find(i=>i.assetId==='gaming_desk'),chair=initial.rooms[0].items.find(i=>i.assetId==='gaming_chair');
 const drag=async(id,dx,dz)=>{await select(id);const p=await page.evaluate(({id,dx,dz})=>{const e=window.__homeEditor,s=e.inspect(),i=s.rooms.flatMap(r=>r.items).find(i=>i.id===id),from=e.projectItem(id),to=e.projectPoint([i.x+dx,i.y+2.5685618729/2,i.z+dz]),r=document.querySelector('.h3-stage').getBoundingClientRect();return {from:{x:from.x+r.left,y:from.y+r.top},to:{x:to.x+r.left,y:to.y+r.top}};},{id,dx,dz});await page.mouse.move(p.from.x,p.from.y);await page.mouse.down();await page.mouse.move(p.to.x,p.to.y,{steps:10});await page.mouse.up();};
 await drag(chair.id,-.35,-.75);let s=await inspect();assert.equal(s.rooms[0].items.find(i=>i.id===chair.id).dockId,desk.id);await page.screenshot({path:'output/furniture-docking/snapped.png'});
 await select(chair.id);await click('rotate');s=await inspect();assert.equal(s.selected,desk.id);assert.equal(s.rotationPreview.rotation,90);await click('place-rotation');s=await inspect();assert.equal(s.rooms[0].items.find(i=>i.id===chair.id).rotation,270);await page.screenshot({path:'output/furniture-docking/rotated-set.png'});
 await click('undo');assert.equal((await inspect()).rooms[0].items.find(i=>i.id===chair.id).rotation,180);await click('redo');assert.equal((await inspect()).rooms[0].items.find(i=>i.id===chair.id).rotation,270);
 await select(desk.id);await click('store');s=await inspect();assert.ok(s.rooms[0].items.every(i=>i.stored));await click('panel','[data-panel="storage"]');assert.equal(await page.locator('[data-action="restore"]').count(),1);await click('restore',`[data-id="${desk.id}"]`);s=await inspect();assert.ok(s.rooms[0].items.every(i=>!i.stored));assert.equal(s.rooms[0].items.find(i=>i.id===chair.id).dockId,desk.id);
 await drag(chair.id,0,1.1);s=await inspect();assert.equal(s.rooms[0].items.find(i=>i.id===chair.id).dockId,null);await click('undo');assert.equal((await inspect()).rooms[0].items.find(i=>i.id===chair.id).dockId,desk.id);
 await select(chair.id);await click('toggle-dock');s=await inspect();assert.equal(s.rooms[0].items.find(i=>i.id===chair.id).dockDisabled,true);await click('toggle-dock');assert.equal((await inspect()).rooms[0].items.find(i=>i.id===chair.id).dockId,desk.id);
 const saved=(await inspect()).rooms;await page.reload();await page.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});assert.deepEqual((await inspect()).rooms,saved);
 // A whole merged floor no longer defeats the furniture detail budget.
 await page.goto('http://127.0.0.1:5174/test/fixtures/room3d-docking.html?dense');await page.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});await page.waitForTimeout(600);const baseline=await inspect();assert.equal(baseline.visibleRoomIds.length,12);assert.equal(baseline.roomGroups.length,1);assert.equal(baseline.detailRooms,3);await page.waitForTimeout(500);assert.equal((await inspect()).renderedFrames,baseline.renderedFrames);
 for(let n=0;n<4;n++){await click('panel','[data-panel="rooms"]');await click('room',`[data-id="room-3-2"]`);await click('panel','[data-panel="rooms"]');await click('room','[data-id="room-0-0"]');}
 await page.waitForTimeout(500);const final=await inspect();for(const k of ['geometries','textures','materials'])assert.equal(final[k],baseline[k],k+' leaked after room switches');assert.ok(final.drawCalls<200);await page.screenshot({path:'output/furniture-docking/twelve-rooms.png'});
 await fs.writeFile('output/furniture-docking/performance.json',JSON.stringify({rooms:12,mergedGroups:final.roomGroups.length,detailed:final.detailRooms,drawCalls:final.drawCalls,triangles:final.triangles,geometries:final.geometries,textures:final.textures,stableResources:true,idleStopped:true},null,2));
 // Visiting a distant room pins its furniture without losing the walk or activity.
 const farDesk=final.rooms.find(r=>r.id==='room-3-0').items.find(i=>i.assetId==='gaming_desk');
 assert.equal(await page.evaluate(id=>window.__homeEditor.projectItem(id),farDesk.id),null);
 const destination=await page.evaluate(async()=>{const {Group}=await import('/node_modules/three/build/three.module.js');window.__homeEditor.setVisitor({root:new Group(),animate(){},dispose(){}});const p=window.__homeEditor.projectPoint([27.9,.18,2.8]),r=document.querySelector('.h3-stage').getBoundingClientRect();return {x:p.x+r.left,y:p.y+r.top};});
 await page.mouse.click(destination.x,destination.y);assert.equal((await inspect()).walking,true);await page.evaluate(()=>window.advanceTime(60000));s=await inspect();assert.equal(s.walking,false);assert.ok(Math.abs(s.visitorLocation.x-27.9)<.1);assert.ok(await page.evaluate(id=>window.__homeEditor.projectItem(id),farDesk.id));
 const otherDesk=final.rooms.find(r=>r.id==='room-3-2').items.find(i=>i.assetId==='gaming_desk');await click('panel','[data-panel="chibi"]');await click('chibi-game',`[data-id="${otherDesk.id}"][data-kind="computer"]`);assert.equal((await inspect()).chibiActivity.itemId,otherDesk.id);assert.ok(await page.evaluate(id=>window.__homeEditor.projectItem(id),otherDesk.id));
 assert.deepEqual(errors,[]);console.log('Dock drag/rotation/history/storage/detach/save, distant walking/activity and merged-floor rendering budgets passed.',final.drawCalls,final.triangles);
}finally{await browser.close();}
