import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
const require=createRequire('C:/Users/tiaotiao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json');
const {chromium}=require('playwright');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-webgl','--no-sandbox']});
const page=await browser.newPage({viewport:{width:430,height:860}}),errors=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto('http://127.0.0.1:4178/assets/editor.html',{waitUntil:'networkidle'});
await page.waitForFunction(()=>window.__homeEditor,{timeout:60000});
await page.screenshot({path:'output/jellyfish-home/editor-initial.png'});
const inspect=()=>page.evaluate(()=>window.__homeEditor.inspect());
const initial=await inspect();
await page.locator('[data-action="edit"]').click();
const sofa=initial.rooms[0].items.find(i=>i.assetId==='sofa');
const screen=await page.evaluate(id=>window.__homeEditor.projectItem(id),sofa.id);
await page.mouse.click(screen.x,screen.y);
await page.locator('[data-action="palette"]').click();await page.locator('[data-action="color"][data-value="#A5B99A"]').click();
await page.screenshot({path:'output/jellyfish-home/editor-color.png'});
const colored=await inspect();
if(colored.rooms[0].items.find(i=>i.id===sofa.id).color!=='#A5B99A')throw Error('Per-item recolor failed');
await page.locator('[data-action="store"]').click();
await page.locator('[data-panel="storage"]').click();
await page.locator('[data-action="restore"]').first().click();
if((await inspect()).rooms[0].items.find(i=>i.id===sofa.id).stored)throw Error('Restore failed');
await page.locator('[data-action="store"]').click();
await page.locator('[data-action="undo"]').click();
if((await inspect()).rooms[0].items.find(i=>i.id===sofa.id).stored)throw Error('Undo failed');
await page.locator('[data-panel="room-style"]').click();
await page.locator('.h3-rename').fill('水母与绿叶');await page.locator('[data-action="rename"]').click();
if((await inspect()).rooms[0].name!=='水母与绿叶')throw Error('Rename failed');
if(await page.locator('[data-action="close"]').count())await page.locator('[data-action="close"]').click();
await page.locator('[data-panel="expand"]').click();await page.locator('[data-direction="right"]').click();
await page.locator('[data-panel="furniture"]').click();await page.locator('[data-action="add-item"][data-id="sofa"]').click();
await page.locator('[data-action="rotate"]').click();await page.locator('[data-action="place-rotation"]').click();
const newRoom=(await inspect()).rooms.at(-1),moving=newRoom.items[0];
if(await page.locator('[data-action="close"]').count())await page.locator('[data-action="close"]').click();
const point=await page.evaluate(id=>window.__homeEditor.projectItem(id),moving.id);
await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+22,point.y+15,{steps:8});await page.mouse.up();
const moved=(await inspect()).rooms.at(-1).items[0];
if(moved.x===moving.x&&moved.z===moving.z)throw Error('Pointer drag failed');
await page.locator('[data-action="store"]').click();
await page.locator('[data-panel="expand"]').click();await page.locator('[data-direction="up"]').click();
await page.locator('[data-panel="storage"]').click();await page.locator('[data-action="restore"]').first().click();
const transfer=await inspect();if(!transfer.rooms.at(-1).items.some(i=>i.id===moving.id))throw Error('Move between rooms via storage failed');
if(await page.locator('[data-action="close"]').count())await page.locator('[data-action="close"]').click();
await page.locator('[data-action="overview"]').click();
await page.screenshot({path:'output/jellyfish-home/editor-overview.png'});
const expanded=await inspect();if(expanded.rooms.length!==3||!expanded.rooms.some(r=>r.level===1))throw Error('Room/floor expansion failed');
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__homeEditor);
if((await inspect()).rooms.length!==3)throw Error('Reload persistence failed');
await page.setViewportSize({width:1100,height:850});await page.locator('[data-action="overview"]').click();
await page.screenshot({path:'output/jellyfish-home/editor-overview-wide.png'});
await writeFile('output/jellyfish-home/editor-qa.json',JSON.stringify({errors,initial,expanded,restored:await inspect()},null,2));
console.log(JSON.stringify({errors,roomCount:expanded.rooms.length,assets:initial.assets.length}));
await browser.close();if(errors.length)process.exitCode=1;
