import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
const require=createRequire('C:/Users/tiaotiao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json');const {chromium}=require('playwright');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--no-sandbox']});
const page=await browser.newPage({viewport:{width:430,height:860},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://127.0.0.1:4178/assets/editor.html');await page.waitForFunction(()=>window.__homeEditor);
const inspect=()=>page.evaluate(()=>window.__homeEditor.inspect());
await page.locator('[data-action="edit"]').click();const first=await inspect(),sofa=first.rooms[0].items.find(i=>i.assetId==='sofa');
let point=await page.evaluate(id=>window.__homeEditor.projectItem(id),sofa.id);await page.mouse.click(point.x,point.y);
if((await inspect()).undoCount!==0||await page.locator('.h3-sheet').count())throw Error('Selecting should not edit or open sheet');
await page.locator('.h3-object-bar').waitFor();const bounds=await page.locator('.h3-object-bar').boundingBox();if(bounds.height>125)throw Error('Selection toolbar too large');
await page.screenshot({path:'output/jellyfish-home/interaction-selected.png'});
await page.locator('[data-action="palette"]').click();await page.locator('[data-action="color"][data-value="#A5B99A"]').click();
await page.locator('[data-action="undo"]').click();if((await inspect()).rooms[0].items.find(i=>i.id===sofa.id).color!==null)throw Error('Undo failed');
await page.locator('[data-action="redo"]').click();if((await inspect()).rooms[0].items.find(i=>i.id===sofa.id).color!=='#A5B99A')throw Error('Redo failed');
await page.locator('[data-action="zoom"]').first().click();const zoom=(await inspect()).zoom;if(zoom<=1)throw Error('Zoom button failed');
await page.mouse.move(200,300);await page.mouse.wheel(0,-100);await page.waitForTimeout(200);if((await inspect()).zoom<=zoom)throw Error('Wheel zoom disabled in edit');
const camera=(await inspect()).cameraPosition;await page.mouse.move(110,200);await page.mouse.down();await page.mouse.move(170,225,{steps:7});await page.mouse.up();await page.waitForTimeout(200);if(JSON.stringify(camera)===JSON.stringify((await inspect()).cameraPosition))throw Error('Blank drag did not orbit');
// Real browser touch input: pinch must work while a furniture item is selected.
await page.evaluate(id=>window.__homeEditor.select(id),sofa.id);point=await page.evaluate(id=>window.__homeEditor.projectItem(id),sofa.id);
const before=await inspect(),cdp=await page.context().newCDPSession(page);
const touch=(x,y,id)=>({x,y,id,radiusX:1,radiusY:1,force:1});
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(170,340,1)]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(170,340,1),touch(240,340,2)]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(145,340,1),touch(270,340,2)]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(200);
const after=await inspect();if(after.zoom===before.zoom||JSON.stringify(after.rooms)!==JSON.stringify(before.rooms))throw Error('Pinch failed or moved furniture');
await page.locator('[data-action="deselect"]').click();await page.locator('[data-panel="expand"]').click();await page.locator('[data-direction="right"]').click();await page.locator('[data-panel="furniture"]').click();await page.locator('[data-action="add-item"][data-id="sofa"]').click();
const start=await inspect(),mover=start.rooms.at(-1).items[0];point=await page.evaluate(id=>window.__homeEditor.projectItem(id),mover.id);
await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x-16,point.y+8,{steps:8});await page.mouse.up();
const moved=await inspect();console.log({point,mover,next:moved.rooms.at(-1).items[0],message:moved.message,cameraBefore:start.cameraPosition,cameraAfter:moved.cameraPosition});await page.screenshot({path:'output/jellyfish-home/interaction-drag.png'});if(moved.rooms.at(-1).items[0].x===mover.x&&moved.rooms.at(-1).items[0].z===mover.z)throw Error('Selected drag failed');
if(JSON.stringify(moved.cameraPosition)!==JSON.stringify(start.cameraPosition)||moved.zoom!==start.zoom)throw Error('Placement reset camera');
await page.screenshot({path:'output/jellyfish-home/interaction-drag.png'});
await writeFile('output/jellyfish-home/interaction-qa.json',JSON.stringify({errors,toolbarHeight:bounds.height,pinchZoom:[before.zoom,after.zoom],dragPassed:true},null,2));console.log({errors,toolbarHeight:bounds.height});await browser.close();if(errors.length)process.exitCode=1;
