const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const b=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader']});
const p=await b.newPage({viewport:{width:1200,height:900}}),errors=[];
p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await p.addInitScript(()=>localStorage.setItem('sully-home3d-quality','balanced'));await p.goto('http://127.0.0.1:5174/test/fixtures/room3d-showrooms.html?room=kitchen&fresh=1',{waitUntil:'domcontentloaded'});
await p.waitForFunction(()=>window.__homeEditor,undefined,{timeout:120000});
const inspect=()=>p.evaluate(()=>window.__homeEditor.inspect()),act=a=>p.locator('[data-action="'+a+'"]').first().click();
await p.evaluate(()=>window.advanceTime(0));await p.screenshot({path:'output/showrooms/finished-kitchen.png'});
let s=await inspect();const counter=s.rooms[0].items.find(i=>i.assetId==='show_kitchen_counter'),children=s.rooms[0].items.filter(i=>i.supportId===counter.id);
assert.equal(children.length,2);await p.evaluate(id=>window.__homeEditor.select(id),counter.id);await act('store');
s=await inspect();assert.ok(s.rooms[0].items.filter(i=>i.supportId===counter.id).every(i=>i.stored));
await act('undo');await act('redo');await act('undo');await p.reload();await p.waitForFunction(()=>window.__homeEditor,undefined,{timeout:120000});
s=await inspect();assert.ok(s.rooms[0].items.filter(i=>i.supportId===counter.id).every(i=>!i.stored));
const pot=s.rooms[0].items.find(i=>i.assetId==='kitchenware_pot');await p.evaluate(id=>window.__homeEditor.select(id),pot.id);await act('palette');
await p.locator('[data-furniture-color]').fill('#d8dadd');await p.locator('[data-furniture-color]').dispatchEvent('change');await act('undo');
assert.equal((await inspect()).rooms[0].items.find(i=>i.id===pot.id).color,null);
const phone=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2,userAgent:'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/120.0.0.0 Mobile Safari/537.36'});
await phone.addInitScript(()=>localStorage.setItem('sully-home3d-quality','balanced'));await phone.goto('http://127.0.0.1:5174/test/fixtures/room3d-showrooms.html?room=kitchen&fresh=1');await phone.waitForFunction(()=>window.__homeEditor,undefined,{timeout:120000});
const mobile=await phone.evaluate(()=>window.__homeEditor.inspect());assert.equal(mobile.rooms[0].items.length,19);assert.equal(mobile.phoneBudget.furniture,20);assert.equal(mobile.windowDaylight.length,1);
await phone.evaluate(()=>window.advanceTime(0));await phone.screenshot({path:'output/showrooms/kitchenware-phone.png'});
assert.deepEqual(errors,[]);await fs.writeFile('output/showrooms/kitchenware-qa.json',JSON.stringify({storageUndoRedo:true,reload:true,paintUndo:true,mobileItems:19,errors},null,2));await b.close();
