import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=await import('file:///C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const catalog=JSON.parse(await fs.readFile('public/room3d/catalog.json','utf8')),assets=catalog.filter(a=>['kitchen','pets'].includes(a.collection));let bytes=0,triangles=0;
for(const a of assets){const b=await fs.readFile('public/room3d/'+a.url),j=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)));assert.ok(!j.images?.length&&!j.textures?.length);assert.ok(b.length<200000,a.id);let t=0;for(const m of j.meshes)for(const p of m.primitives){assert.ok(!p.attributes.TEXCOORD_0&&!p.attributes.COLOR_0);t+=j.accessors[p.indices].count/3;}assert.ok(t<6000,a.id);bytes+=b.length;triangles+=t;}
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader']});const errors=[];await fs.mkdir('output/kitchen',{recursive:true});
try{
 const page=await browser.newPage({viewport:{width:1100,height:850},deviceScaleFactor:1.5});page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.addInitScript(()=>localStorage.setItem('sully-home3d-quality','clear'));
 await page.goto('http://127.0.0.1:5174/test/fixtures/room3d-kitchen.html');await page.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});
 const inspect=()=>page.evaluate(()=>window.__homeEditor.inspect()),click=async(a,q='')=>{if(a==='panel'&&(await inspect()).panel===q.match(/data-panel="([^"]+)/)?.[1])return;await page.locator('[data-action="'+a+'"]'+q).first().click()},select=id=>page.evaluate(id=>window.__homeEditor.select(id),id);
 const handState=()=>page.evaluate(()=>{const h=[];window.__visitor.root.traverse(o=>{if(o.name.startsWith('chibi-hand-')||o.name.startsWith('chibi-action-'))h.push({name:o.name,visible:o.visible,position:o.position.toArray(),scale:o.scale.toArray(),geometry:Array.from(o.geometry.attributes.position.array)});});return h;});
 const rest=await handState();await click('panel','[data-panel="chibi"]');assert.equal(await page.locator('[data-kind="eat"]:enabled').count(),2);await click('chibi-game','[data-kind="eat"]');await page.evaluate(()=>window.advanceTime(700));const a=await handState();await page.evaluate(()=>window.advanceTime(600));const b=await handState();assert.notDeepEqual(a.map(h=>h.position),b.map(h=>h.position));for(let i=0;i<rest.length;i++){assert.deepEqual(rest[i].scale,b[i].scale);assert.deepEqual(rest[i].geometry,b[i].geometry);}
 assert.equal((await inspect()).chibiPosture,'seated');assert.equal((await inspect()).kitchen.mealVisible,true);
 assert.equal(b.filter(h=>h.name.startsWith('chibi-action-')&&h.visible).length,4);assert.equal(b.filter(h=>h.name.startsWith('chibi-hand-')&&h.visible).length,0);assert.ok(rest.filter(h=>h.name.startsWith('chibi-action-')).every(h=>!h.visible));
 // The actual bowl bottom sits above the rendered tabletop, not merely its metadata.
 assert.ok(await page.evaluate(async()=>{const T=await import('/node_modules/three/build/three.module.js');const r=window.__visitor.root.parent,s=window.__homeEditor.inspect();r.parent.updateMatrixWorld(true);let table;r.parent.traverse(o=>{if(o.userData.itemId===s.chibiActivity.itemId&&o.userData.assetId)table=o;});return new T.Box3().setFromObject(r.getObjectByName('meal-bowl')).min.y>new T.Box3().setFromObject(table).max.y;}));
 await click('panel','[data-panel="chibi"]');await click('chibi-view');await click('turn-view','[data-angle=".785398"]');await page.screenshot({path:'output/kitchen/eating-side.png'});await click('turn-view','[data-angle=".785398"]');await page.screenshot({path:'output/kitchen/eating-front.png'});
 await page.evaluate(()=>window.advanceTime(12500));assert.equal((await inspect()).chibiActivity,null);assert.equal((await inspect()).chibiPosture,'seated');assert.equal((await inspect()).kitchen.mealVisible,false);
 await click('panel','[data-panel="chibi"]');await click('chibi-motion','[data-value="wave-calm"]');await page.evaluate(()=>window.advanceTime(400));const waving=await handState();await page.evaluate(()=>window.advanceTime(350));const waved=await handState();assert.notDeepEqual(waving.find(h=>h.name==='chibi-action-hand-1').position,waved.find(h=>h.name==='chibi-action-hand-1').position);assert.equal((await inspect()).chibiPosture,'seated');await click('close');await click('turn-view','[data-angle=".785398"]');await page.screenshot({path:'output/kitchen/seated-wave.png'});
 await click('panel','[data-panel="chibi"]');await click('chibi-stand');assert.equal((await inspect()).chibiPosture,'standing');const standing=await handState();assert.ok(standing.filter(h=>h.name.startsWith('chibi-action-')).every(h=>!h.visible));assert.ok(standing.filter(h=>h.name.startsWith('chibi-hand-')).every(h=>h.visible));
 await click('panel','[data-panel="chibi"]');await click('room-view');await select('fridge');await click('fridge-toggle');await page.evaluate(()=>window.advanceTime(600));let open=await inspect();assert.equal(open.kitchen.openId,'fridge');assert.ok(open.kitchen.angles.every(a=>Math.abs(a)>1.4));await page.screenshot({path:'output/kitchen/fridge-open.png'});
 await click('fridge-toggle');await page.evaluate(()=>window.advanceTime(600));assert.equal((await inspect()).kitchen.openId,null);assert.ok((await inspect()).kitchen.angles.every(a=>Math.abs(a)<.001));
 const warm=await inspect();for(let n=0;n<4;n++){await click('fridge-toggle');await page.evaluate(()=>window.advanceTime(600));await click('fridge-toggle');await page.evaluate(()=>window.advanceTime(600));}assert.equal((await inspect()).geometries,warm.geometries);assert.equal((await inspect()).textures,warm.textures);
 await click('fridge-toggle');await page.evaluate(()=>window.advanceTime(600));await click('store');assert.equal((await inspect()).kitchen.openId,null);await click('undo');await select('fridge');await click('rotate');await click('place-rotation');await click('fridge-toggle');await page.evaluate(()=>window.advanceTime(600));assert.equal((await inspect()).kitchen.openId,'fridge');
 await click('panel','[data-panel="furniture"]');await click('catalog-mode','[data-value="use"]');await click('category','[data-value="pets"]');assert.equal(await page.locator('.h3-asset').count(),1);await page.screenshot({path:'output/kitchen/pets-category.png'});await click('catalog-mode','[data-value="room"]');await click('category','[data-value="kitchen"]');assert.equal(await page.locator('.h3-asset').count(),14);
 const mobile=await browser.newPage({viewport:{width:390,height:844},screen:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2,userAgent:'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 Chrome/120.0.0.0 Mobile Safari/537.36'});mobile.on('pageerror',e=>errors.push(String(e)));await mobile.goto('http://127.0.0.1:5174/test/fixtures/room3d-kitchen.html?kind=empty');await mobile.waitForFunction(()=>window.__homeEditor,undefined,{timeout:90000});await mobile.locator('[data-panel="furniture"]').click();await mobile.locator('[data-action="category"][data-value="kitchen"]').click();await mobile.locator('[data-action="dining-preset"]').click();assert.equal((await mobile.evaluate(()=>window.__homeEditor.inspect())).rooms[0].items.length,3);await mobile.locator('[data-action="undo"]').click();assert.equal((await mobile.evaluate(()=>window.__homeEditor.inspect())).rooms[0].items.length,0);await mobile.locator('[data-action="redo"]').click();assert.equal((await mobile.evaluate(()=>window.__homeEditor.inspect())).rooms[0].items.length,3);await mobile.screenshot({path:'output/kitchen/mobile-preset.png'});await mobile.close();
 assert.deepEqual(errors,[]);await fs.writeFile('output/kitchen/qa-report.json',JSON.stringify({assets:assets.length,bytes,triangles,eatingRigidHands:true,actionLimbs:true,fridgeHinges:true,resourceReuse:true,mobilePresetUndoRedo:true,errors},null,2));console.log('Kitchen budgets, floating limbs, dining, fridge animation/rotation/storage, categories, mobile preset undo/redo and resource reuse passed');
}finally{await browser.close();}
