import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.ROOM3D_PLAYWRIGHT_MODULE||'playwright'),b=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader']});
try{const p=await b.newPage({viewport:{width:1100,height:850}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));await mkdir('output/rotation',{recursive:true});await p.goto('http://127.0.0.1:5174/test/fixtures/room3d-rotation.html');await p.waitForFunction(()=>window.__homeEditor);
 const inspect=()=>p.evaluate(()=>window.__homeEditor.inspect()),click=a=>p.locator(`[data-action="${a}"]`).click();await p.evaluate(()=>window.__homeEditor.select('cabinet'));const initial=await inspect();
 await click('rotate');let state=await inspect();assert.equal(state.rotationPreview.rotation,90);assert.deepEqual(state.rooms,initial.rooms);assert.equal(state.undoCount,0);assert.ok(!/碰到|放在地板内/.test(state.message));await p.screenshot({path:'output/rotation/preview.png'});
 await click('place-rotation');state=await inspect();assert.match(state.message,/放在地板内/);assert.deepEqual(state.rooms,initial.rooms);assert.equal(state.rotationPreview.rotation,90);await p.screenshot({path:'output/rotation/blocked-drop.png'});
 const from=await p.evaluate(()=>window.__homeEditor.projectItem('cabinet'));
 // Project a lower floor position using the same orthographic view; the grab
 // offset is preserved by moving along the camera-projected +Z direction.
 const delta=await p.evaluate(async()=>{const T=await import('/node_modules/three/build/three.module.js'),s=window.__homeEditor.inspect(),r=document.querySelector('.h3-stage').getBoundingClientRect(),ratio=r.width/r.height,h=Math.max(10.1,10.1/ratio),c=new T.OrthographicCamera(-h*ratio/2,h*ratio/2,h/2,-h/2,.1,200);c.position.fromArray(s.cameraPosition);c.lookAt(0,2,0);c.zoom=s.zoom;c.updateProjectionMatrix();c.updateMatrixWorld();const a=new T.Vector3(0,0,0).project(c),z=new T.Vector3(0,0,1.9).project(c);return {x:(z.x-a.x)*r.width/2,y:-(z.y-a.y)*r.height/2};});
 await p.mouse.move(from.x,from.y);await p.mouse.down();await p.mouse.move(from.x+delta.x,from.y+delta.y,{steps:18});await p.mouse.up();state=await inspect();assert.equal(state.rotationPreview,null);assert.equal(state.rooms[0].items[0].rotation,90);assert.equal(state.undoCount,1);assert.equal(state.rooms[0].items[1].rotation,90);assert.match(state.message,/已放好/);await p.screenshot({path:'output/rotation/placed.png'});
 await click('undo');assert.deepEqual((await inspect()).rooms,initial.rooms);await click('redo');assert.equal((await inspect()).rooms[0].items[0].rotation,90);
 await p.evaluate(()=>window.__homeEditor.select('cabinet'));const beforeCancel=await inspect();await click('rotate');await click('cancel-rotation');assert.deepEqual((await inspect()).rooms,beforeCancel.rooms);assert.equal((await inspect()).undoCount,beforeCancel.undoCount);
 await click('rotate');await p.keyboard.press('Escape');assert.equal((await inspect()).rotationPreview,null);assert.deepEqual((await inspect()).rooms,beforeCancel.rooms);
 await p.goto('http://127.0.0.1:5174/test/fixtures/room3d-rotation.html?collision=1');await p.waitForFunction(()=>window.__homeEditor);await p.evaluate(()=>window.__homeEditor.select('cabinet'));await click('rotate');assert.ok(!/碰到/.test((await inspect()).message));assert.equal((await inspect()).rotationPreview.rotation,90);await click('place-rotation');assert.match((await inspect()).message,/碰到龟背竹/);assert.equal((await inspect()).rooms[0].items[0].rotation,0);
 assert.deepEqual(errors,[]);console.log('ROTATION_PASS: unrestricted unsaved preview, collision only on drop, valid drag commits parent+props once, undo/redo, cancel and Escape.');
}finally{await b.close();}
