import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
const require=createRequire('C:/Users/tiaotiao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json');
const {chromium}=require('playwright');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--no-sandbox']});
const page=await browser.newPage({viewport:{width:430,height:860}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://127.0.0.1:4178/assets/editor.html');await page.waitForFunction(()=>window.__homeEditor);
const state=()=>page.evaluate(()=>window.__homeEditor.getState());
const choose=async id=>page.evaluate(id=>window.__homeEditor.select(id),id);
const close=async()=>{if(await page.locator('[data-action="close"]').count())await page.locator('[data-action="close"]').click()};
await page.locator('[data-panel="expand"]').click();await page.locator('[data-direction="right"]').click();
await page.locator('[data-panel="furniture"]').click();await page.locator('[data-action="category"][data-value="all"]').click();
await page.locator('[data-action="add-item"][data-id="tea_mug"]').click();
if(!(await page.locator('.h3-status').textContent()).includes('台面'))throw Error('Missing tabletop error');
await page.locator('[data-action="category"][data-value="table"]').click();await page.locator('[data-action="add-item"][data-id="worktable"]').click();await close();
await page.locator('[data-panel="furniture"]').click();await page.locator('[data-action="category"][data-value="all"]').click();await page.locator('[data-action="add-item"][data-id="tea_mug"]').click();
let room=(await state()).rooms.at(-1),desk=room.items.find(i=>i.assetId==='worktable'),cup=room.items.find(i=>i.assetId==='tea_mug');
if(cup.supportId!==desk.id)throw Error('Cup unsupported');
await choose(desk.id);await page.locator('[data-action="rotate"]').click();await page.locator('[data-action="place-rotation"]').click();
room=(await state()).rooms.at(-1);if(room.items.find(i=>i.id===cup.id).rotation!==90)throw Error('Cup did not follow rotation');
await page.locator('[data-action="store"]').click();if((await state()).rooms.at(-1).items.some(i=>!i.stored))throw Error('Group not stored');
await page.locator('[data-panel="expand"]').click();await page.locator('[data-direction="up"]').click();await page.locator('[data-panel="storage"]').click();await page.locator(`[data-action="restore"][data-id="${desk.id}"]`).click();
room=(await state()).rooms.at(-1);if(room.items.length!==2||room.items.some(i=>i.stored)||room.items.find(i=>i.id===cup.id).supportId!==desk.id)throw Error('Group restore failed');
await choose(cup.id);await page.locator('[data-action="store"]').click();await page.locator('[data-panel="storage"]').click();await page.locator(`[data-action="restore"][data-id="${cup.id}"]`).click();
await page.reload();await page.waitForFunction(()=>window.__homeEditor);room=(await state()).rooms.at(-1);if(room.items.find(i=>i.id===cup.id)?.supportId!==desk.id)throw Error('Support not saved');
await page.locator('[data-panel="furniture"]').click();await page.locator('[data-action="category"][data-value="all"]').click();await page.screenshot({path:'output/jellyfish-home/support-editor.png'});
await writeFile('output/jellyfish-home/support-qa.json',JSON.stringify({errors,room},null,2));console.log({errors,supported:room.items.length});await browser.close();if(errors.length)process.exitCode=1;
