import {it,expect} from 'vitest';
import JSZip from 'jszip';
import {DB,openDB} from './db';
import {saveLibraryDecoration,readLibraryDecorations,readDecorationOrigin} from './decorationLibrary';
import {bindBeautySource,readBeautyBinding} from './beautySourceBinding';
import {rememberBeautyAuthor,readRememberedBeautyAuthor} from './beautyAuthorBackup';
import {writeV2Backup,assembleV2Backup} from './backupFormat';
import {collectBlobRefs,writeBlobsToZip,readBlobsIndex,restoreBlobsFromZip} from './backupBlobs';
import {migrateDataUrlToRef,getBlobForRef,restoreBlobRef} from './blobRef';
it('restores outfit identity, files, attribution, binding and personal preferences from a real backup archive',async()=>{
 const preset={format:'sullyos-chat-decoration' as const,version:1 as const,name:'搬家搭配',parts:{css:'.sully-chat-root {color:red}',background:{image:'data:image/png;base64,AA==',style:'plain' as const},psyche:{styleId:'echo' as const,customCss:'.sully-psyche-card{color:red}'},sound:{src:'pop',volume:.4}}};
 const id=await saveLibraryDecoration(preset,{kind:'self',credit:'作者'},undefined,'outfit');
 const image=await migrateDataUrlToRef('data:image/webp;base64,UklGRgAAAABXRUJQ');
 const bubble={id:'old-workshop-bubble',name:'旧工坊气泡',type:'custom',user:{backgroundImage:image},ai:{backgroundColor:'white'}} as any;
 await DB.saveTheme(bubble);
 const related={'decoration_slots_sample':JSON.stringify({bubbles:id}),'decoration_applied_sample':id,'decoration_global_schedule':'schedule-source','decoration_global_journal':'journal-source','icon_vrworld':image,'wallpaper':image};
 for(const [key,value] of Object.entries(related))await DB.saveAsset(key,value);
 const binding={sourceId:id,fingerprint:'test',revision:'one'} as any;await bindBeautySource('A-0123456789ABCDEF','submission',binding);
 rememberBeautyAuthor('A-0123456789ABCDEF','test-password-1234');localStorage.setItem('sully-beauty-repo-status-v1',JSON.stringify({'S-0123456789AB':'manual'}));
 localStorage.setItem('sully_chrome_css_presets_v1',JSON.stringify([{name:'旧白框',code:'.sully-chat-root{color:blue}'}]));
 const exported=await DB.exportFullData();const archive=new JSZip();const refs=new Set<string>();await writeV2Backup(archive,exported as any,{onSerialized:json=>collectBlobRefs(json,refs)});
 expect((await writeBlobsToZip(archive,refs,getBlobForRef)).missing).toEqual([]);
 const bytes=await archive.generateAsync({type:'uint8array'});const zip=await JSZip.loadAsync(bytes);const restored=await assembleV2Backup(zip,JSON.parse(await zip.file('manifest.json')!.async('string')));
 const db=await openDB();await new Promise<void>((resolve,reject)=>{const tx=db.transaction('assets','readwrite');tx.objectStore('assets').clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});localStorage.clear();
 await DB.importFullData(restored as any);
 const blobIndex=await readBlobsIndex(zip);expect(blobIndex.length).toBeGreaterThan(0);
 await restoreBlobsFromZip(zip,blobIndex,restoreBlobRef);
 expect((await getBlobForRef(image))?.type).toBe('image/webp');
 expect((await DB.getThemes()).find(p=>p.id===bubble.id)).toEqual(bubble);
 for(const [key,value] of Object.entries(related))expect(await DB.getAsset(key)).toBe(value);
 expect(await DB.getAssetRaw('chrome_css_presets')).toEqual([{name:'旧白框',code:'.sully-chat-root{color:blue}'}]);
 const list=await readLibraryDecorations();expect(list.find(p=>p._libraryId===id)).toMatchObject({...preset,_collection:'outfit'});
 expect(await readDecorationOrigin(id)).toMatchObject({kind:'self',credit:'作者'});expect(await readBeautyBinding('A-0123456789ABCDEF','submission')).toEqual(binding);
 expect(readRememberedBeautyAuthor()?.authorCode).toBe('A-0123456789ABCDEF');expect(JSON.parse(localStorage.getItem('sully-beauty-repo-status-v1')!)['S-0123456789AB']).toBe('manual');
});
