import type { EmbeddingConfig, MemoryNode, RemoteVectorConfig } from './memoryPalace/types';
import { vectorizeAndStore } from './memoryPalace';
import { classifyGameHallMemory, gameHallImportance } from './gameHallMemoryPolicy';
import type { GameHallEvent, GameHallMemoryCandidate, GameHallMemorySignal } from './gameHallMemoryTypes';
import { writeGameHallBridgeSnapshot } from './gameHallMemoryBridge';
import { gameHallId, getGameHallEvents, getPendingGameHallMemoryCandidates, saveGameHallEvent, saveGameHallMemoryCandidate, saveGameHallPreferenceEvidence } from './gameHallStore';
const hasEmbedding=(c?:EmbeddingConfig)=>Boolean(c?.baseUrl&&c?.apiKey&&c?.model&&c.dimensions>0);
export async function recordGameHallMemoryEvent(input:{sessionId:string;charId:string;kind:GameHallEvent['kind'];text:string;signal?:GameHallMemorySignal;sourceMessageIds?:string[];gameId?:string;gameName?:string}):Promise<GameHallEvent>{
 const decision=classifyGameHallMemory(input.text,input.signal); const event:GameHallEvent={id:gameHallId('ghevent'),sessionId:input.sessionId,charId:input.charId,createdAt:Date.now(),kind:input.kind,summary:decision.summary,level:decision.level,category:decision.category,signals:decision.signals,sourceMessageIds:input.sourceMessageIds,gameId:input.gameId,gameName:input.gameName}; await saveGameHallEvent(event);
 if(event.category==='preference'||event.category==='boundary') await saveGameHallPreferenceEvidence({id:gameHallId('ghpref'),charId:event.charId,sessionId:event.sessionId,eventId:event.id,summary:event.summary,createdAt:event.createdAt,polarity:event.category==='boundary'?'boundary':/不喜欢|讨厌|避免/.test(event.summary)?'avoid':'prefer'});
 if(event.level===3) await saveGameHallMemoryCandidate({id:gameHallId('ghcandidate'),sessionId:event.sessionId,charId:event.charId,eventIds:[event.id],content:event.summary,category:event.category,importance:gameHallImportance(event.category,event.signals),createdAt:event.createdAt,updatedAt:event.createdAt,status:'pending',gameId:event.gameId,gameName:event.gameName});
 return event;
}
export async function buildGameHallSessionSummary(input:{sessionId:string;charId:string;gameId?:string;gameName?:string;force?:boolean}):Promise<GameHallEvent|undefined>{
 const events=(await getGameHallEvents(input.sessionId)).filter(x=>x.kind!=='session_summary'&&!x.summarizedAt&&x.level>0); if(!input.force&&events.length<12)return; if(!events.length)return; const notable=events.filter(x=>x.level>=2); const summary=(notable.length?notable:events).slice(-20).map(x=>x.summary).join('；').slice(0,1800); const node:GameHallEvent={id:gameHallId('ghsummary'),sessionId:input.sessionId,charId:input.charId,createdAt:Date.now(),kind:'session_summary',summary,level:2,category:'current_context',signals:['session_summary'],sourceMessageIds:events.flatMap(x=>x.sourceMessageIds||[]),gameId:input.gameId,gameName:input.gameName}; await saveGameHallEvent(node); await writeGameHallBridgeSnapshot({sessionId:input.sessionId,charId:input.charId,summary:`我们共同游戏的阶段摘要：${summary}`,eventIds:events.map(x=>x.id)}); for(const e of events){e.summarizedAt=node.createdAt;await saveGameHallEvent(e);} return node;
}
export async function flushGameHallMemoryCandidates(input:{charId:string;embedding?:EmbeddingConfig;remote?:RemoteVectorConfig}):Promise<{stored:number;skipped:number;pending:number}>{
 let remote=input.remote; if(!remote&&typeof localStorage!=='undefined'){try{const parsed=JSON.parse(localStorage.getItem('os_remote_vector_config')||'null');if(parsed?.enabled&&parsed?.initialized)remote=parsed;}catch{/* local vector write remains available */}} const candidates=await getPendingGameHallMemoryCandidates(input.charId); if(!hasEmbedding(input.embedding))return {stored:0,skipped:0,pending:candidates.length}; let stored=0,skipped=0;
 for(const c of candidates){const now=Date.now();const node:MemoryNode={id:gameHallId('memory'),charId:c.charId,content:c.content,room:'living_room',tags:['game-hall',c.category],importance:c.importance,mood:'shared',embedded:false,createdAt:c.createdAt,lastAccessedAt:now,accessCount:0,origin:'system',gameHallSource:{sessionId:c.sessionId,eventIds:c.eventIds,gameId:c.gameId,gameName:c.gameName}}; try{const r=await vectorizeAndStore([node],input.embedding!,remote);c.updatedAt=Date.now();if(r.stored){c.status='stored';c.memoryNodeId=node.id;stored++;}else{c.status='deduplicated';skipped++;}delete c.error;await saveGameHallMemoryCandidate(c);}catch(e:any){c.error=(e?.message||String(e)).slice(0,500);c.updatedAt=Date.now();await saveGameHallMemoryCandidate(c);}}
 return {stored,skipped,pending:(await getPendingGameHallMemoryCandidates(input.charId)).length};
}
