import {describe,it,expect} from 'vitest';import fs from 'node:fs';
import catalog from '../public/room3d/catalog.json';import {bedroomHome} from '../test/fixtures/bedroom-layout.js';import {roomBeds,seatTransform} from '../apps/room3d/seating.js';import {roomPlush,plushPose} from '../apps/room3d/plush.js';import {placementError,validateHome,moveFurniture,furnitureType} from '../apps/room3d/model.js';
describe('bedroom furniture and hugs',()=>{
 it('ships 47 light geometry-only assets with real paint targets',()=>{const assets=catalog.filter(a=>a.id.startsWith('bedroom_'));expect(assets).toHaveLength(47);for(const a of assets){const b=fs.readFileSync('public/room3d/'+a.url),j=JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString());expect(b.length,a.id).toBeLessThan(200000);expect(j.images?.length||0).toBe(0);expect(j.textures?.length||0).toBe(0);expect(a.paintMaterials?.every(n=>j.materials.some(m=>m.name===n)),a.id).toBe(true);let triangles=0;for(const m of j.meshes)for(const p of m.primitives){expect(p.attributes.TEXCOORD_0).toBeUndefined();expect(p.attributes.COLOR_0).toBeUndefined();triangles+=j.accessors[p.indices].count/3;}expect(triangles,a.id).toBeLessThan(6000);}});
 it('fits the same 15-piece bedroom around every bed and preserves storage round trips',()=>{for(const a of catalog.filter(a=>a.beds)){const h=bedroomHome(catalog,a.id),r=h.rooms[0];expect(r.items).toHaveLength(15);expect(r.items.map(i=>[i.id,placementError(i,r,catalog)]).filter(v=>v[1])).toEqual([]);expect(validateHome(h,catalog).rooms).toEqual(h.rooms);}});
 it('resolves every bed position through rotation and drops stored beds',()=>{for(const a of catalog.filter(a=>a.beds)){const h=bedroomHome(catalog,a.id),r=h.rooms[0];r.items=r.items.filter(i=>i.assetId===a.id);const positions=roomBeds(r,catalog);expect(positions.length).toBe(a.beds.length);for(const b of positions){const base=a.beds.find(v=>v.id===b.seatId),x=a.id==='show_bed'?Math.sign(base.position[0])*.70:base.position[0],z=base.position[2]+(a.id==='show_bed'?.35:0);for(const rotation of [0,90,180,270]){moveFurniture(r,a.id,{x:0,z:0,rotation},catalog);const t=seatTransform(r,catalog,b),angle=rotation*Math.PI/180;expect(t.position[0]).toBeCloseTo(x*Math.cos(angle)+z*Math.sin(angle));expect(t.position[2]).toBeCloseTo(-x*Math.sin(angle)+z*Math.cos(angle));}}r.items[0].stored=true;expect(roomBeds(r,catalog)).toEqual([]);expect(seatTransform(r,catalog,positions[0])).toBeNull();}});
 it('uses a distinct plush category and keeps hugs substantial but below the face',()=>{const dolls=catalog.filter(a=>a.holdable);expect(dolls).toHaveLength(4);for(const a of dolls){expect(furnitureType(a)).toBe('plush');const p=plushPose(a,1);expect(a.size[0]*p.scale).toBeGreaterThan(.5);expect(a.size[0]*p.scale).toBeLessThanOrEqual(.79);expect(p.position[1]+a.size[1]*p.scale).toBeLessThan(.94);expect(p.position[2]-a.size[2]*p.scale/2).toBeCloseTo(.39);expect(p.hands[0][0]).toBe(-p.hands[1][0]);}const r=bedroomHome(catalog).rooms[0];expect(roomPlush(r,catalog)).toHaveLength(1);r.items.find(i=>i.assetId==='bedroom_jelly').stored=true;expect(roomPlush(r,catalog)).toHaveLength(0);});
});

