import {describe,it,expect} from 'vitest';
import catalog from '../public/room3d/catalog.json';
import {createHome} from '../apps/room3d/model.js';
import {createPetLife,normalizePetLife,petMap,choosePetAction} from '../apps/room3d/petLife.js';
const setup=()=>{let home=createHome(catalog);home.rooms[0].items=[];const life=createPetLife({home:()=>home,catalog,random:()=>.5});return {life,get home(){return home;},replace:(value:any)=>{home=value;}};};
describe('local home pets',()=>{
 it('adopts all seven species as distinct living entities and validates saved data',()=>{const s=setup();for(const a of catalog.filter(a=>'petSpecies' in a))s.life.adopt(a.id,a.name,['playful']);expect(s.home.rooms[0].items).toHaveLength(0);expect(new Set(s.life.data.pets.map(p=>p.id)).size).toBe(7);expect(()=>s.life.adopt('pet_cat','第八只')).toThrow();const restored=normalizePetLife(JSON.parse(JSON.stringify(s.life.data)),s.home,catalog);expect(restored.pets).toEqual(s.life.data.pets.map(p=>({...p,memory:{lastFedBy:null,lastPlayedBy:null,favoriteSpot:null,recentAction:null}})));});
 it('does not reward interrupted interactions, rewards completion once and pauses needs',()=>{const {life}=setup(),p=life.adopt('pet_cat','团子');life.data.autonomy=false;life.interact(p.id,'feed');const before=structuredClone(p.needs);life.step(1,false);expect(p.needs).toEqual(before);expect(p.memory.lastFedBy).toBeUndefined();expect(()=>life.interact(p.id,'feed')).toThrow();for(let i=0;i<6;i++)life.step(1);expect(p.needs.food).toBeGreaterThan(before.food);expect(p.memory.lastFedBy).toBe('user');expect(p.relations.user).toBe(2);for(let i=0;i<10;i++)life.step(1);expect(p.relations.user).toBe(2);});
 it('keeps pets in their room when the camera changes and preserves life across layout undo',()=>{const s=setup(),p=s.life.adopt('pet_dog','小狗'),snapshot=structuredClone(s.home);p.needs.food=22;s.replace(snapshot);s.life.reconcile();expect(s.home.petLife.pets[0].needs.food).toBe(22);s.home.rooms.push({...structuredClone(s.home.rooms[0]),id:'other',x:1});s.home.activeRoomId='other';const old=structuredClone(p);for(let i=0;i<40;i++)s.life.step(1);expect(p).toEqual(old);});
 it('conversion retains color and cannot be duplicated by furniture undo',()=>{const s=setup(),room=s.home.rooms[0];room.items.push({id:'ornament',assetId:'pet_turtle',x:0,y:.15,z:0,rotation:0,color:'#123456',stored:false} as any);const before=structuredClone(s.home);const p=s.life.adopt('pet_turtle','龟',['lazy'],'ornament');expect(p.color).toBe('#123456');expect(room.items).toHaveLength(0);s.replace(before);s.life.reconcile();expect(s.home.rooms[0].items).toHaveLength(0);expect(s.life.data.pets).toHaveLength(1);});
 it('does not walk through furniture or out of the assigned room',()=>{const s=setup(),p=s.life.adopt('pet_cat','猫');s.home.rooms[0].items=[{id:'table',assetId:'table',x:0,y:.15,z:0,rotation:0,color:null,stored:false} as any];const map=petMap(s.home.rooms[0],catalog,p);expect(map.free(0,0)).toBe(false);expect(map.free(4.6,0)).toBe(false);expect(map.free(3,2)).toBe(true);});
 it('filters empty bowls and reserves food until actual completion',()=>{const s=setup(),p=s.life.adopt('pet_cat','猫');s.home.rooms[0].items.push({id:'bowl',assetId:'pet_bowls',x:-2,y:.15,z:-2,rotation:0,color:null,stored:false} as any);expect(s.life.candidates(p).some(a=>a.kind==='eat')).toBe(false);s.life.refill('bowl');expect(s.life.candidates(p).some(a=>a.kind==='eat')).toBe(true);p.x=-2;p.z=-.85;s.life.runtime.set(p.id,{kind:'eat',itemId:'bowl',path:[],phase:0,duration:6});s.life.step(1);expect(s.life.data.supplies.bowl).toBe(5);for(let i=0;i<5;i++)s.life.step(1);expect(s.life.data.supplies.bowl).toBe(4);});
 it('makes weighted choices among top candidates and applies personality',()=>{const s=setup(),p=s.life.adopt('pet_cat','猫',['greedy']);p.needs.food=5;const candidates=[{kind:'eat'},{kind:'sleep'},{kind:'play'},{kind:'wander'}];expect(choosePetAction(candidates,p,()=>0).kind).toBe('eat');expect(choosePetAction(candidates,p,()=>.999).kind).not.toBe('eat');});
 it('sanitizes corrupt imported numbers and unknown color slots',()=>{const s=setup(),p=s.life.adopt('pet_cat','猫');const raw=structuredClone(s.life.data);raw.pets[0].needs.food=Infinity;raw.pets[0].x=NaN;raw.pets[0].materialColors={'pet-body':'#112233',unknown:'#abcdef'};raw.pets.push({...p});const result=normalizePetLife(raw,s.home,catalog);expect(result.pets).toHaveLength(1);expect(result.pets[0].needs.food).toBe(75);expect(result.pets[0].x).toBe(0);expect(result.pets[0].materialColors).toEqual({'pet-body':'#112233'});});
 it('cancels a moved or removed station without granting remote rewards',()=>{const s=setup(),p=s.life.adopt('pet_cat','猫');s.home.rooms[0].items.push({id:'bowl',assetId:'pet_bowls',x:-2,y:.15,z:-2,rotation:0,color:null,stored:false} as any);s.life.refill('bowl');p.x=-2;p.z=-.85;const food=p.needs.food;s.life.runtime.set(p.id,{kind:'eat',itemId:'bowl',targetPosition:[-2,-2],path:[],phase:5.8,duration:6});s.home.rooms[0].items[0].x=2;s.life.step(.3);expect(p.needs.food).toBeLessThan(food);expect(s.life.data.supplies.bowl).toBe(5);expect(s.life.runtime.has(p.id)).toBe(false);});
 it('limits relationship rewards across repeated completed interactions',()=>{const {life}=setup(),p=life.adopt('pet_cat','猫');life.data.autonomy=false;for(const kind of ['pet','play','feed']){life.interact(p.id,kind);for(let i=0;i<6;i++)life.step(1);}expect(p.relations.user).toBe(2);expect(p.memory.lastPlayedBy).toBe('user');expect(p.memory.lastFedBy).toBe('user');});
 it('remembers a real rest mat and does not invent unreachable interactions',()=>{const s=setup(),p=s.life.adopt('pet_turtle','龟');s.home.rooms[0].items.push({id:'mat',assetId:'pet_rest_mat',x:2,y:.15,z:2,rotation:0,color:null,stored:false} as any);s.life.reconcile();expect(s.life.candidates(p).some(c=>c.kind==='sleep'&&c.itemId==='mat')).toBe(true);p.x=2;p.z=2;s.life.runtime.set(p.id,{kind:'sleep',itemId:'mat',targetPosition:[2,2],path:[],phase:17,duration:18});s.life.step(1);expect(p.memory.favoriteSpot).toBe('mat');});
 it('excludes busy residents and uses stable identities for real proximity',()=>{const home=createHome(catalog);home.rooms[0].items=[];let busy=true;const life=createPetLife({home:()=>home,catalog,actors:()=>[{id:'char-a',roomId:home.activeRoomId,x:2,z:0,busy}]});const p=life.adopt('pet_cat','猫',['clingy']);expect(life.candidates(p).some(a=>a.actorId==='char-a')).toBe(false);busy=false;expect(life.candidates(p).some(a=>a.actorId==='char-a')).toBe(true);life.runtime.set(p.id,{kind:'attention',actorId:'char-a',path:[],phase:5.9,duration:6});life.step(.2);expect(p.relations['char-a']).toBeUndefined();});
});

it('calls a pet from another room, then approaches the user without granting an early reward',()=>{
 const home=createHome(catalog);home.rooms[0].items=[];home.rooms.push({...structuredClone(home.rooms[0]),id:'other',x:1});
 const life=createPetLife({home:()=>home,catalog,actors:()=>[{id:'user',roomId:home.activeRoomId,x:2,z:0,busy:true}]});
 const p=life.adopt('pet_cat','团子');home.activeRoomId='other';life.interact(p.id,'approach');
 expect(p.roomId).toBe('other');expect(life.runtime.get(p.id)?.kind).toBe('approach');expect(p.relations.user).toBeUndefined();
});


it('full-home restore replaces live pets and pending actions; layout undo still preserves life',()=>{
 const s=setup(),old=s.life.adopt('pet_cat','旧猫');s.life.interact(old.id,'feed');
 const before=structuredClone(s.home),other=setup();const dog=other.life.adopt('pet_dog','备份的狗');dog.needs.food=21;dog.relations.user=9;
 const imported=structuredClone(other.home),dataIdentity=s.life.data;
 s.replace(imported);s.life.restore(imported.petLife);s.life.attach();s.life.reconcile();
 expect(s.life.data).toBe(dataIdentity);expect(s.life.runtime.size).toBe(0);
 expect(s.home.petLife.pets).toHaveLength(1);expect(s.home.petLife.pets[0]).toMatchObject({id:dog.id,needs:{food:21},relations:{user:9}});
 const redo=structuredClone(s.home);s.replace(before);s.life.restore(before.petLife);s.life.attach();
 expect(s.home.petLife.pets[0].id).toBe(old.id);
 s.replace(redo);s.life.restore(redo.petLife);s.life.attach();expect(s.home.petLife.pets[0].id).toBe(dog.id);
 const empty=createHome(catalog);s.replace(empty);s.life.restore(undefined);s.life.attach();expect(s.home.petLife.pets).toEqual([]);
});
