#!/usr/bin/env node
// node >= 20
//
// Builds every esbuild-bundled Worker in the WORKERS manifest. Dual-output:
//   worker/<name>/worker.bundle.js   ← user copies this into the CF dashboard
//   public/<outName>                 ← vite ships to dist/, Modal fetch reads it
//
// Adding a new Worker:
//   1. drop the entry at worker/<new>/src/index.ts
//   2. add a row to WORKERS below
//   3. that's it — `npm run build` (which chains to build:workers) picks it up
//
// Why a manifest array instead of auto-discover: worker/proactive-push/ has
// src/index.ts + wrangler.toml too, but its worker.bundle.js is hand-written
// (not an esbuild artifact). A naive scan of worker/*/src/index.ts would
// silently overwrite it. The manifest is explicit about which workers go
// through this pipeline.

import { build } from 'esbuild';
import { existsSync, statSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const WORKERS = [
  { name: 'instant-push', outName: 'instant-worker.bundle.js' },
];

// amsg-instant 0.3.0+ uses only Web Crypto (globalThis.crypto.subtle); the
// bundle has zero Node crypto imports, so CF Workers / Vercel Edge / Netlify
// Edge run with no compatibility flags and no runtime polyfill.
const sharedOpts = {
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  bundle: true,
  minify: false,
  conditions: ['worker', 'browser', 'import', 'default'],
};

console.log(`Building ${WORKERS.length} worker bundle(s)...`);

for (const w of WORKERS) {
  const entry = resolve(root, 'worker', w.name, 'src/index.ts');
  if (!existsSync(entry)) {
    console.error(`ERROR: entry not found for "${w.name}": ${entry}`);
    process.exit(1);
  }

  const outWorker = resolve(root, 'worker', w.name, 'worker.bundle.js');
  const outPublic = resolve(root, 'public', w.outName);
  const banner = { js: `/* generated by scripts/build-workers.mjs — do not edit by hand */` };

  await build({ ...sharedOpts, entryPoints: [entry], outfile: outWorker, banner });
  await build({ ...sharedOpts, entryPoints: [entry], outfile: outPublic, banner });

  const workerSize = statSync(outWorker).size;
  console.log(`✓ ${w.name.padEnd(16)} ${(workerSize / 1024).toFixed(1)} KB  → worker/${w.name}/worker.bundle.js + public/${w.outName}`);
}
