import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, GameController, GearSix, LinkSimple, PaperPlaneRight, ShieldCheck, X } from '@phosphor-icons/react';
import { useOS } from '../context/OSContext';
import SensitiveTextInput from '../components/SensitiveTextInput';
import CedarToySurface from '../components/gameHall/CedarToySurface';
import { buildCedarCapabilityMap, clearCedarConnection, describeCedarCapabilities, diagnoseCedarConnection, loadCedarConnection, saveCedarConnection } from '../utils/cedarToyMcpAdapter';
import { executePendingGameHallAction, planGameHallTurn, readCedarGameState } from '../utils/gameHallAgent';
import { writeGameHallBridgeSnapshot } from '../utils/gameHallMemoryBridge';
import { buildGameHallSessionSummary, flushGameHallMemoryCandidates, recordGameHallMemoryEvent } from '../utils/gameHallMemoryCoordinator';
import { gameHallId, getActiveGameHallSession, getGameHallMessages, getPendingGameHallActions, saveGameHallMessage, saveGameHallSession, savePendingGameHallAction } from '../utils/gameHallStore';
import type { CedarCapabilityMap, CedarToyConnection, GameHallCompanionMode, GameHallMessage, GameHallPendingAction, GameHallSession, GameHallWebState, NormalizedCedarGameState } from '../utils/gameHallTypes';

const MODES: Array<{ id: GameHallCompanionMode; label: string }> = [{ id:'observe',label:'只观察'},{ id:'ask-before-action',label:'行动前询问'},{ id:'auto-turn',label:'自动回合'}];
const GameHallApp: React.FC = () => {
  const { closeApp, characters, activeCharacterId, isLocked, apiConfig, userProfile, memoryPalaceConfig } = useOS();
  const [charId,setCharId]=useState(activeCharacterId||characters[0]?.id||''); const [mode,setMode]=useState<GameHallCompanionMode>('ask-before-action');
  const [settingsOpen,setSettingsOpen]=useState(false); const [connection,setConnection]=useState<CedarToyConnection>(()=>loadCedarConnection());
  const [capabilities,setCapabilities]=useState<CedarCapabilityMap|null>(()=>connection.tools?buildCedarCapabilityMap(connection.tools):null); const [testing,setTesting]=useState(false); const [diagnostic,setDiagnostic]=useState('尚未测试连接');
  const [webState,setWebState]=useState<GameHallWebState>({url:'https://toy.cedarstar.org/',loading:true}); const [session,setSession]=useState<GameHallSession|null>(null);
  const [messages,setMessages]=useState<GameHallMessage[]>([]); const [pending,setPending]=useState<GameHallPendingAction[]>([]); const [gameState,setGameState]=useState<NormalizedCedarGameState>();
  const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const listRef=useRef<HTMLDivElement>(null); const selected=useMemo(()=>characters.find(c=>c.id===charId)||characters[0],[characters,charId]);
  const handleWebState=useCallback((state:GameHallWebState)=>setWebState(state),[]);
  const append=async(role:GameHallMessage['role'],content:string,toolName?:string)=>{if(!session||!selected)return; const msg={id:gameHallId('ghmsg'),sessionId:session.id,charId:selected.id,role,content,toolName,createdAt:Date.now()}; await saveGameHallMessage(msg); setMessages(v=>[...v,msg]); return msg;};
  useEffect(()=>{if(!selected)return; let alive=true;(async()=>{let current=await getActiveGameHallSession(selected.id); if(!current){const now=Date.now();current={id:gameHallId('ghsession'),charId:selected.id,mode,status:'active',createdAt:now,updatedAt:now};await saveGameHallSession(current);} if(!alive)return;setSession(current);setMode(current.mode);setMessages(await getGameHallMessages(current.id));setPending(await getPendingGameHallActions(current.id));})();return()=>{alive=false};},[selected?.id]);
  useEffect(()=>{listRef.current?.scrollTo({top:listRef.current.scrollHeight});},[messages,pending]);
  const changeMode=async(next:GameHallCompanionMode)=>{setMode(next);if(session){const updated={...session,mode:next,updatedAt:Date.now()};setSession(updated);await saveGameHallSession(updated);}};
  const refreshState=async()=>{setBusy(true);try{const read=await readCedarGameState(connection);setGameState(read.state);if(session){const updated={...session,lastStateHash:read.state.stateHash,gameId:read.state.gameId,gameName:read.state.gameName,updatedAt:Date.now()};setSession(updated);await saveGameHallSession(updated);}await append('tool',`已通过 ${read.toolName} 读取同一存档状态。`,read.toolName);return read.state;}catch(e:any){await append('system',e?.message||String(e));throw e;}finally{setBusy(false);}};
  const executeAction=async(action:GameHallPendingAction,automatic=false)=>{setBusy(true);const running={...action,status:'confirmed' as const,updatedAt:Date.now()};await savePendingGameHallAction(running);try{const result=await executePendingGameHallAction(connection,running);if(!result.success)throw new Error(result.error||'行动失败');const done={...running,status:'executed' as const,updatedAt:Date.now()};await savePendingGameHallAction(done);setPending(v=>v.filter(x=>x.id!==action.id));await append('tool',`${automatic?'自动回合':'已确认'}执行 ${action.toolName} 成功。`,action.toolName);const actionSummary=`我和${selected?.name||'角色'}刚刚在 Cedar Toy 共同游戏；${selected?.name||'角色'}${automatic?'按自动回合规则':'经我确认'}执行了 ${action.toolName}，原因：${action.reason}。`;await writeGameHallBridgeSnapshot({sessionId:action.sessionId,charId:action.charId,summary:actionSummary});await recordGameHallMemoryEvent({sessionId:action.sessionId,charId:action.charId,kind:'action',text:actionSummary,gameId:session?.gameId,gameName:session?.gameName});await refreshState();}catch(e:any){const failed={...running,status:'failed' as const,error:e?.message||String(e),updatedAt:Date.now()};await savePendingGameHallAction(failed);await append('system',`行动失败：${failed.error}`);}finally{setBusy(false);}};
  const cancelAction=async(action:GameHallPendingAction)=>{await savePendingGameHallAction({...action,status:'cancelled',updatedAt:Date.now()});setPending(v=>v.filter(x=>x.id!==action.id));};
  const send=async()=>{const text=input.trim();if(!text||!session||!selected||busy)return;setInput('');setBusy(true);try{const userMsg=await append('user',text);await recordGameHallMemoryEvent({sessionId:session.id,charId:selected.id,kind:'user_message',text,sourceMessageIds:userMsg?[userMsg.id]:[],gameId:session.gameId,gameName:session.gameName});let state=gameState;try{state=await readCedarGameState(connection).then(x=>x.state);setGameState(state);}catch{/* Agent can still chat without state */}const plan=await planGameHallTurn({apiConfig,char:selected,userProfile,mode,userText:text,state,actionTools:capabilities?.action||[],sessionId:session.id});const assistantMsg=await append('assistant',plan.reply);await recordGameHallMemoryEvent({sessionId:session.id,charId:selected.id,kind:'assistant_message',text:plan.reply,signal:plan.memorySignal,sourceMessageIds:assistantMsg?[assistantMsg.id]:[],gameId:state?.gameId||session.gameId,gameName:state?.gameName||session.gameName});await buildGameHallSessionSummary({sessionId:session.id,charId:selected.id,gameId:state?.gameId||session.gameId,gameName:state?.gameName||session.gameName});await flushGameHallMemoryCandidates({charId:selected.id,embedding:memoryPalaceConfig.embedding});if(plan.pending){if(mode==='auto-turn'&&state?.allowsAiAction&&session.lastAutoActionStateHash!==state.stateHash){const updated={...session,lastAutoActionStateHash:state.stateHash,updatedAt:Date.now()};setSession(updated);await saveGameHallSession(updated);await executeAction(plan.pending,true);}else{await savePendingGameHallAction(plan.pending);setPending(v=>[...v,plan.pending!]);}}}catch(e:any){await append('system',e?.message||String(e));}finally{setBusy(false);}};
  const finishSession=async()=>{if(session&&selected){await buildGameHallSessionSummary({sessionId:session.id,charId:selected.id,gameId:session.gameId,gameName:session.gameName,force:true});await flushGameHallMemoryCandidates({charId:selected.id,embedding:memoryPalaceConfig.embedding});await saveGameHallSession({...session,status:'ended',updatedAt:Date.now()});}closeApp();};
  const testConnection=async()=>{setTesting(true);setDiagnostic('正在执行 initialize 与 tools/list…');const result=await diagnoseCedarConnection(connection);setTesting(false);if(!result.ok){setDiagnostic(`连接失败：${result.message}`);return;}const next={...connection,tools:result.tools||[],updatedAt:Date.now()};setConnection(next);saveCedarConnection(next);const map=result.capabilities||buildCedarCapabilityMap(result.tools||[]);setCapabilities(map);setDiagnostic(`${result.message}。${!map.state.length?'连接成功，但暂未识别出游戏状态工具。':!map.action.length?'已识别状态工具，但暂未识别行动工具。':'已识别状态与行动能力。'}`);};
  return <div className="relative flex h-full min-h-0 flex-col bg-[radial-gradient(circle_at_top,#312e81,#0f172a_48%,#020617)] text-white" style={{paddingTop:'var(--chrome-top)',paddingBottom:'var(--safe-bottom)'}}>
    <header className="flex h-14 shrink-0 items-center gap-3 px-3"><button onClick={()=>void finishSession()} className="rounded-xl p-2"><ArrowLeft size={22}/></button><GameController size={25} weight="fill" className="text-violet-300"/><div className="min-w-0 flex-1"><h1 className="font-bold">游戏厅</h1><p className="truncate text-[10px] text-slate-400">Cedar Toy · {webState.loading?'加载中':webState.title||'已打开'}</p></div><button onClick={()=>setSettingsOpen(true)} className="p-2"><GearSix size={22}/></button></header>
    <main className="flex min-h-0 flex-1 flex-col gap-2 px-2 pb-2"><CedarToySurface suspended={settingsOpen||isLocked} onState={handleWebState}/><section className="flex max-h-[45%] min-h-[210px] shrink-0 flex-col rounded-2xl border border-white/10 bg-slate-900/95 p-3"><div className="flex items-center gap-2">{selected?.avatar?<img src={selected.avatar} className="h-9 w-9 rounded-full object-cover"/>:<span>🎮</span>}<select value={charId} onChange={e=>setCharId(e.target.value)} className="min-w-0 flex-1 rounded-xl bg-slate-800 p-2 text-sm">{characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button disabled={busy||!capabilities?.state.length} onClick={()=>void refreshState()} className="rounded-lg bg-slate-800 px-2 py-2 text-[11px] disabled:opacity-40">读状态</button></div><div className="mt-2 grid grid-cols-3 gap-1 rounded-xl bg-black/20 p-1">{MODES.map(x=><button key={x.id} onClick={()=>void changeMode(x.id)} className={`rounded-lg py-1.5 text-[11px] ${mode===x.id?'bg-violet-500':'text-slate-400'}`}>{x.label}</button>)}</div>
      <div ref={listRef} className="mt-2 min-h-0 flex-1 space-y-2 overflow-y-auto text-xs">{messages.slice(-30).map(m=><div key={m.id} className={`rounded-xl px-3 py-2 ${m.role==='user'?'ml-8 bg-violet-600':m.role==='assistant'?'mr-8 bg-slate-800':'bg-black/25 text-slate-400'}`}>{m.content}</div>)}{pending.map(a=><div key={a.id} className="rounded-xl border border-amber-400/30 bg-amber-950/40 p-3"><b>建议行动：{a.toolName}</b><p className="my-1 text-slate-300">{a.reason}</p><div className="flex gap-2"><button disabled={busy} onClick={()=>void executeAction(a)} className="rounded-lg bg-emerald-600 px-3 py-1.5">确认执行</button><button onClick={()=>void cancelAction(a)} className="rounded-lg bg-slate-700 px-3 py-1.5">取消</button></div></div>)}</div>
      <div className="mt-2 flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} placeholder="和角色讨论这一局…" className="min-w-0 flex-1 rounded-xl bg-slate-800 px-3 py-2 text-sm"/><button disabled={busy||!input.trim()} onClick={()=>void send()} className="rounded-xl bg-violet-600 p-2 disabled:opacity-40"><PaperPlaneRight size={20}/></button></div></section></main>
    {settingsOpen&&<div className="absolute inset-0 z-50 flex items-end bg-black/60" onClick={()=>setSettingsOpen(false)}><div className="max-h-[88%] w-full overflow-y-auto rounded-t-3xl bg-slate-950 p-5" onClick={e=>e.stopPropagation()}><div className="mb-4 flex items-center"><div className="flex-1"><h2 className="font-bold">Cedar Toy MCP</h2><p className="text-xs text-slate-400">只依据真实 tools/list 与 schema</p></div><button onClick={()=>setSettingsOpen(false)}><X size={22}/></button></div><label className="mb-3 block text-xs">MCP URL<input value={connection.url} onChange={e=>setConnection(v=>({...v,url:e.target.value}))} className="mt-1 w-full rounded-xl bg-slate-900 p-3" inputMode="url"/></label><label className="mb-3 block text-xs">Bearer Token<SensitiveTextInput value={connection.token||''} onChange={e=>setConnection(v=>({...v,token:e.target.value}))} className="mt-1 w-full rounded-xl bg-slate-900 p-3"/></label><div className="grid grid-cols-2 gap-2"><button disabled={testing} onClick={()=>void testConnection()} className="flex items-center justify-center gap-2 rounded-xl bg-violet-600 p-3 text-sm"><LinkSimple/>{testing?'测试中…':'测试连接'}</button><button onClick={()=>saveCedarConnection({...connection,updatedAt:Date.now()})} className="rounded-xl bg-slate-800 p-3 text-sm">保存</button></div><div className="mt-4 rounded-2xl bg-slate-900 p-4 text-xs"><div className="mb-2 flex gap-2 font-semibold"><ShieldCheck/>协议诊断</div><p>{diagnostic}</p>{capabilities&&<ul className="mt-2 text-slate-400">{describeCedarCapabilities(capabilities).map(x=><li key={x}>• {x}</li>)}</ul>}</div><button onClick={()=>{clearCedarConnection();setConnection({url:'',updatedAt:0});setCapabilities(null)}} className="mt-4 w-full rounded-xl border border-red-400/30 p-3 text-red-300">清除连接</button></div></div>}
  </div>;
};
export default GameHallApp;
