import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=await import('file:///C:/Users/tiaotiao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1200,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.route('**/@vite/client', route=>route.fulfill({contentType:'application/javascript',body:`export function createHotContext(){return {on(){},off(){},accept(){},dispose(){},prune(){},invalidate(){},data:{}}} const sheets=new Map();export function updateStyle(id,css){let e=sheets.get(id);if(!e){e=document.createElement('style');document.head.append(e);sheets.set(id,e);}e.textContent=css;}export function removeStyle(id){sheets.get(id)?.remove();sheets.delete(id);}export function injectQuery(url){return url;}`}));
 await page.goto('http://127.0.0.1:5174/test/fixtures/home-pets.html');await page.waitForFunction(()=>window.__homeEditor?.inspect().social.residents.some(r=>r.id==='user'&&r.visible),{timeout:120000});
 await page.evaluate(()=>{const e=window.__homeEditor,s=e.getPetSystem();s.life.data.autonomy=false;s.life.runtime.clear();e.advanceTime(6000);});
 await page.locator('.h3-pets-entry').click();await page.locator('[data-pet-action=select]').nth(3).click();await page.locator('[data-kind=pet]').click();
 console.log('START',await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact),await page.locator('[role=alert]').allTextContents());
 for(let i=0;i<200;i++){await page.evaluate(()=>window.advanceTime(100));const c=await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact);if(c?.phase==='stroke'&&c.time>1.5)break;}
 await page.evaluate(()=>{window.__homeEditor.setViewMode('free');window.__homeEditor.openPanel('chibi');});await page.locator('[data-action=chibi-view]').click();await page.evaluate(()=>window.__homeEditor.advanceTime(0));await page.screenshot({path:'output/pets/life/contact-stroke.png'});const stroke=await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact);console.log('CONTACT ERROR',Math.hypot(...stroke.hands[0].map((v,i)=>v-stroke.targets[0][i])));assert.ok(Math.hypot(...stroke.hands[0].map((v,i)=>v-stroke.targets[0][i]))<.12);console.log('STROKE',await page.evaluate(()=>({contact:window.__homeEditor.getPetSystem().inspect().contact,actor:window.__homeEditor.inspect().chibiPosition})));
 await page.evaluate(()=>window.advanceTime(7000));assert.equal(await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact),null);
 await page.locator('.h3-pets-entry').click();await page.locator('[data-pet-action=select]').nth(3).click();await page.locator('[data-kind=carry]').click();
 for(let i=0;i<160;i++){await page.evaluate(()=>window.advanceTime(100));if(await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact?.phase==='held'))break;}
 assert.equal(await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact?.phase),'held');const held=await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact);assert.ok(held.hands.every((p,i)=>Math.hypot(...p.map((v,k)=>v-held.targets[i][k]))<.09));await page.screenshot({path:'output/pets/life/contact-held.png'});
 console.log('HELD',await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact));
 await page.evaluate(()=>window.__homeEditor.setSuspended(true));const paused=await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact.time);await page.evaluate(()=>window.advanceTime(3000));assert.equal(await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact.time),paused);await page.evaluate(()=>window.__homeEditor.setSuspended(false));
 await page.evaluate(()=>window.__homeEditor.openPanel('chibi'));await page.getByRole('button',{name:'看全屋',exact:true}).click();await page.evaluate(()=>window.__homeEditor.advanceTime(0));
 const ground=await page.evaluate(()=>window.__homeEditor.projectPoint([-1,.18,-1.8]));await page.mouse.click(ground.x,ground.y);await page.evaluate(()=>window.advanceTime(1000));assert.equal(await page.evaluate(()=>window.__homeEditor.inspect().walking),true);console.log('WALK',await page.evaluate(()=>({walking:window.__homeEditor.inspect().walking,contact:window.__homeEditor.getPetSystem().inspect().contact})));await page.screenshot({path:'output/pets/life/contact-walk.png'});
 await page.locator('[data-drop]').click();await page.evaluate(()=>window.advanceTime(1000));await page.screenshot({path:'output/pets/life/contact-lower.png'});await page.evaluate(()=>window.advanceTime(2000));assert.equal(await page.evaluate(()=>window.__homeEditor.getPetSystem().inspect().contact),null);
 await page.setViewportSize({width:390,height:844});await page.locator('.h3-pets-entry').click();await page.locator('[data-pet-action=select]').last().click();await page.screenshot({path:'output/pets/life/contact-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.keyboard.press('Escape');
 assert.deepEqual(errors,[]);console.log('Contact browser QA passed');
}finally{await browser.close();}
