import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.ROOM3D_PLAYWRIGHT_MODULE||'file:///C:/Users/tiaotiao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
await fs.mkdir('output/pets/life',{recursive:true});const errors=[];
try{
 const page=await browser.newPage({viewport:{width:1240,height:850}});page.on('pageerror',e=>errors.push(String(e)));
  await page.route('**/@vite/client', route=>route.fulfill({contentType:'application/javascript',body:`export function createHotContext(){return {on(){},off(){},accept(){},dispose(){},prune(){},invalidate(){},data:{}}} const sheets=new Map();export function updateStyle(id,css){let e=sheets.get(id);if(!e){e=document.createElement('style');document.head.append(e);sheets.set(id,e);}e.textContent=css;}export function removeStyle(id){sheets.get(id)?.remove();sheets.delete(id);}export function injectQuery(url){return url;}`}));
 await page.goto('http://127.0.0.1:5174/test/fixtures/room3d-pet-life.html');await page.waitForFunction(()=>window.__homeEditor,{timeout:120000});
 assert.equal(await page.evaluate(()=>window.__homeEditor.getState().petLife.pets.length),7);
 await page.screenshot({path:'output/pets/life/room.png'});
 await page.locator('.h3-pets-entry').click();await page.screenshot({path:'output/pets/life/roster.png'});await page.locator('[data-pet-action=select]').nth(3).click();
 await page.locator('[data-pet-action=detail-tab][data-tab=look]').click();await page.locator('[data-pet-name]').fill('橘子');await page.locator('[data-pet-name]').press('Tab');
 await page.locator('[data-pet-action=detail-tab][data-tab=look]').click();await page.locator('[data-value="cat-2"]').click();
 assert.equal(await page.evaluate(()=>window.__homeEditor.getState().petLife.pets[3].name),'橘子');
 const colors=await page.evaluate(()=>window.__homeEditor.getState().petLife.pets[3].materialColors);assert.ok(colors['pet-body']);
 await page.locator('[data-pet-action=detail-tab][data-tab=care]').click();await page.locator('[data-pet-action=interact][data-kind=feed]').click();assert.equal(await page.locator('[data-action-progress]').isVisible(),true);assert.equal(await page.locator('[data-kind=play]').isDisabled(),true);
 await page.evaluate(()=>window.advanceTime(6100));
 await page.waitForFunction(()=>document.querySelector('[data-pet-feedback]')?.textContent.includes('完成'));assert.equal(await page.locator('[data-kind=play]').isEnabled(),true);const fed=await page.evaluate(()=>window.__homeEditor.getState().petLife.pets[3]);assert.equal(fed.memory.lastFedBy,'user');assert.equal(fed.relations.user,2);
 await page.screenshot({path:'output/pets/life/panel.png'});
 const before=await page.evaluate(()=>{window.__homeEditor.setSuspended(true);return JSON.stringify(window.__homeEditor.getState().petLife.pets);});
 await page.evaluate(()=>window.advanceTime(20000));assert.equal(await page.evaluate(()=>JSON.stringify(window.__homeEditor.getState().petLife.pets)),before);
 await page.evaluate(()=>window.__homeEditor.setSuspended(false));await page.reload();await page.waitForFunction(()=>window.__homeEditor,{timeout:120000});
 const reloaded=await page.evaluate(()=>window.__homeEditor.getState().petLife.pets[3]);assert.equal(reloaded.id,fed.id);assert.equal(reloaded.name,'橘子');assert.deepEqual(reloaded.materialColors,colors);assert.equal(reloaded.memory.lastFedBy,'user');
 await page.locator('.h3-pets-entry').click();await page.locator('[data-pet-action=select]').nth(3).click();await page.locator('[data-pet-action=detail-tab][data-tab=look]').click();await page.locator('[data-action=reset-all-colors]').click();
 await page.locator('[data-material-color="pet-eyes"]').fill('#112233');assert.equal(await page.evaluate(()=>window.__homeEditor.getState().petLife.pets[3].materialColors['pet-eyes']),'#112233');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'output/pets/life/mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('[data-pet-action=back]').click();await page.locator('summary').filter({hasText:'认识新伙伴'}).click();await page.locator('form[data-pet-adopt] button').click();assert.match(await page.locator('[role=alert]').textContent(),/最多/);
 await page.keyboard.press('Escape');assert.equal(await page.locator('.h3-pets-overlay').isVisible(),false);
 await page.setViewportSize({width:1240,height:850});
 await page.goto('http://127.0.0.1:5174/test/fixtures/room3d-building.html');await page.waitForFunction(()=>window.__homeEditor,{timeout:120000});
 await page.locator('.h3-pets-entry').click();await page.locator('select[name=asset]').selectOption('pet_cat');await page.locator('input[name=name]').fill('新来的团子');await page.locator('input[name=trait][value=clingy]').check();await page.locator('form[data-pet-adopt] button').click();
 assert.equal(await page.evaluate(()=>window.__homeEditor.getState().petLife.pets[0].name),'新来的团子');
 await page.locator('[data-pet-action=close]').click();
 await page.goto('http://127.0.0.1:5174/test/fixtures/home-pets.html');await page.waitForFunction(()=>window.__homeEditor?.inspect().social.residents.some(r=>r.id==='user'&&r.visible),{timeout:120000});
 await page.evaluate(()=>{const e=window.__homeEditor;e.advanceTime(6000);e.openPanel('rooms');});
 const roomBefore=await page.evaluate(()=>window.__homeEditor.getState().petLife.pets.map(p=>p.roomId));
 await page.locator('[data-action=room]').first().click();await page.evaluate(()=>window.advanceTime(10000));
 assert.deepEqual(await page.evaluate(()=>window.__homeEditor.getState().petLife.pets.map(p=>p.roomId)),roomBefore);
 await page.evaluate(()=>window.__homeEditor.openPanel('rooms'));await page.locator('[data-action=room]').last().click();
 await page.locator('.h3-pets-entry').click();await page.locator('[data-pet-action=select]').nth(3).click();await page.locator('[data-pet-action=interact][data-kind=approach]').click();
 assert.equal(await page.locator('[role=alert]').count(),0);
 await page.evaluate(()=>window.advanceTime(20000));
 const called=await page.evaluate(()=>window.__homeEditor.getState().petLife.pets[3]);assert.ok(called.relations.user>0);
 await page.locator('[data-pet-action=close]').click();
 const petPoint=await page.evaluate(()=>{const e=window.__homeEditor,system=e.getPetSystem();system.life.data.autonomy=false;system.life.runtime.clear();const p=system.life.data.pets[5];return e.projectPoint([p.x,.4,p.z]);});
 await page.mouse.click(petPoint.x,petPoint.y);await page.locator('[data-action=pet-panel]').click();assert.equal(await page.locator('.h3-pets-sheet h2').textContent(),'圆壳小龟');await page.locator('[data-pet-action=close]').click();
 await page.screenshot({path:'output/pets/life/production.png'});
 await page.setViewportSize({width:390,height:844});await page.locator('.h3-pets-entry').click();await page.screenshot({path:'output/pets/life/production-mobile.png'});
 assert.deepEqual(errors,[]);console.log('Pet browser QA passed: seven pets, feeding completion, pause, palette/reset/custom, reload, mobile, capacity, Escape.');
}finally{await browser.close();}
