import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const {chromium}=await import('file:///C:/Users/tiaotiao/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{
 const page=await browser.newPage({viewport:{width:1240,height:850}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.route('**/@vite/client', route=>route.fulfill({contentType:'application/javascript',body:`export function createHotContext(){return {on(){},off(){},accept(){},dispose(){},prune(){},invalidate(){},data:{}}} const sheets=new Map();export function updateStyle(id,css){let e=sheets.get(id);if(!e){e=document.createElement('style');document.head.append(e);sheets.set(id,e);}e.textContent=css;}export function removeStyle(id){sheets.get(id)?.remove();sheets.delete(id);}export function injectQuery(url){return url;}`}));
 await page.goto('http://127.0.0.1:5174/test/fixtures/room3d-pet-life.html',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForFunction(()=>window.__homeEditor,{timeout:120000});
 await page.evaluate(()=>{const e=window.__homeEditor,s=e.getPetSystem();s.life.data.autonomy=false;s.life.runtime.clear();e.advanceTime(10000);});
 let clickedId;async function clickPet(){const point=await page.evaluate(()=>{const e=window.__homeEditor,p=e.getPetSystem().life.data.pets[innerWidth<600?1:5];return e.projectPoint([p.x,.4,p.z]);});await page.mouse.click(point.x,point.y);await page.waitForFunction(()=>!!window.__homeEditor.inspect().interaction?.petId);clickedId=await page.evaluate(()=>window.__homeEditor.inspect().interaction.petId);}
 await clickPet();assert.equal(await page.locator('.h3-pets-overlay').isVisible(),false);assert.equal(await page.locator('[data-action=pet-panel]').count(),1);assert.equal(await page.locator('.social-petal').count(),4);await page.waitForTimeout(600);await page.screenshot({path:'output/pets/life/pet-wheel.png'});
 await page.locator('[data-action=pet-panel]').click();assert.equal(await page.locator('.h3-pets-sheet h2').textContent(),await page.evaluate(id=>window.__homeEditor.getPetSystem().life.data.pets.find(p=>p.id===id).name,clickedId));await page.keyboard.press('Escape');
 await clickPet();await page.locator('[data-action=interaction-more]').click();assert.equal(await page.locator('.social-wheel-page-count').textContent(),'2/2');await page.locator('[data-action=interaction-back]').click();assert.equal(await page.locator('[data-action=pet-panel]').count(),1);await page.locator('[data-action=interaction-more]').click();assert.equal(await page.locator('[data-action=pet-interact][data-kind=play]').count(),1);await page.locator('[data-action=pet-interact][data-kind=play]').click();assert.equal(await page.locator('.h3-pets-overlay').isVisible(),false);assert.equal(await page.evaluate(id=>window.__homeEditor.getPetSystem().life.runtime.get(id)?.kind,clickedId),'play');await page.evaluate(()=>window.advanceTime(6100));
 await clickPet();await page.locator('[data-action=pet-interact][data-kind=pet]').click();assert.equal(await page.locator('.h3-pets-overlay').isVisible(),false);const physical=await page.evaluate(()=>({contact:window.__homeEditor.getPetSystem().inspect().contact,message:window.__homeEditor.inspect().message}));assert.ok(physical.contact||physical.message);if(physical.contact)await page.locator('[data-cancel]').click();else await page.keyboard.press('Escape');
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);await page.evaluate(()=>window.__homeEditor.advanceTime(0));await clickPet();await page.waitForTimeout(600);await page.screenshot({path:'output/pets/life/pet-wheel-mobile.png'});
 const rects=await page.locator('.social-petal').evaluateAll(nodes=>nodes.map(n=>{const b=n.getBoundingClientRect();return {x:b.x,y:b.y,right:b.right,bottom:b.bottom};}));assert.ok(rects.every(b=>b.x>=0&&b.right<=390&&b.y>=0&&b.bottom<=844));await page.locator('[data-action=interaction-back]').click();assert.equal(await page.locator('.h3-interaction').isVisible(),false);await clickPet();await page.keyboard.press('Escape');assert.equal(await page.locator('.h3-interaction').isVisible(),false);
 assert.deepEqual(errors,[]);console.log('Pet wheel QA passed: mesh click, panel action, paged direct interaction, petting dispatch, mobile bounds, Escape.');
}finally{await browser.close();}



